# Cubo Gelatinoso
Heloísa Fernandes Cano - T26

O seguinte projeto consiste na primeira entrega da disciplina de Aprendizado de Máquina, ministrada pelo professor doutor Daniel Roberto Casar, durante o 2º semestre de 2026 no curso de Bacharelado em Ciência e Tecnologia da Ilum - Escola de Ciência.


## Enunciado

### Objetivo

<b>Objetivo:</b> Escolha um conjunto de dados que siga as considerações abaixo e estude o desempenho de modelos induzidos pelo algoritmo de <i>k</i> vizinhos mais próximos neste conjunto de dados
considerando diferentes conjuntos de hiperparâmetros (pelo menos 10 conjuntos de hiperparâmetros
diferentes). A entrega deve ser realizada em um notebook de Jupyter. A sugestão é que esta seja uma
entrega com texto direto, sem a necessidade de longos parágrafos. É necessário utilizar o `scikit‑learn`
para induzir os modelos de <i>k</i> vizinhos mais próximos. Não se esqueça de justificar a métrica de
desempenho escolhida.

### Considerações

<b>Considerações:</b> O conjunto de dados deve ter as seguintes características:
- Pelo menos 5 atributos. Destes atributos, pelo menos um deles deve ser categórico
- Pelo menos 1 target (não há necessidade de mais que 1 target e pode ser um target categórico
ou numérico, a sua escolha)
- Pelo menos 150 exemplos
- Os dados não podem ser sintéticos


### Expectativas

<b>Expectativas:</b> É esperado que o trabalho siga as boas práticas apresentadas na disciplina, apresente
resultados de forma gráfica, use seções bem nomeadas e bem divididas no notebook de Jupyter e
encerre a entrega com uma seção chamada “Conclusões e principais aprendizados”. O trabalho deve
ter uma seção chamada “Descrição do uso de IA neste trabalho” detalhando como foi a interação com
ferramentas de IA para a construção dos textos e códigos.

### Pontuação base

<b>Pontuação base:</b> 7 (válida apenas caso o objetivo tenha sido realizado)
Descontos usuais da pontuação base:
- Alguma expectativa não foi atingida
- Trabalho não seguiu boas práticas apresentadas na disciplina. Lembre‑se de revisar o material
apresentado e suas anotações durante a aula
- Trabalho não apresentou resultados de forma gráfica
- Não guiou o leitor na entrega
- Não interpretou e discutiu os resultados
- Gráfico sem legenda em um ou mais eixos
- Código que acusa erro ao rodar na ordem de cima para baixo
- Entrega sem referências
- Uso incorreto ou omisso de citações (incluindo falta de citação sobre uso de IA)
- Não soube explicar sobre estratégias e códigos utilizados na entrega
- Respostas incorretas às perguntas realizadas pelo professor durante o momento avaliativo
- Respostas incorretas às perguntas realizadas pelo Perguntador 2000™ durante o momento
avaliativo
- Atraso na entrega do trabalho no Teams

### Pontuação complementar

<b>Pontuação complementar:</b> 3 (cada item abaixo pode valer até no máximo 1 ponto)
- Realizou uma boa análise exploratória dos dados e comparou o desempenho dos modelos com
relação a um modelo baseline
- Checou como o desempenho dos modelos varia utilizando ou não utilizando dados normalizados de diferentes maneiras
- Checou o desempenho dos modelos variando o número de vizinhos
- Checou o desempenho dos modelos variando a função de distância (considerando pelo menos
3 funções diferentes)
- Checou o desempenho dos modelos variando a estratégia de codificação do(s) atributo(s) categórico(s)



### Observações e Lembretes

<b>Motivação e aprendizado:</b> Esta é uma tarefa introdutória da disciplina, sendo assim, a motivação
principal é justamente iniciar sua jornada no campo do Aprendizado de Máquina.

<b>Sugestão de uso de IA nesta tarefa:</b> Um bom uso de IA pode ser para encontrar conjuntos
de dados de seu interesse. Fora isso, debater com a IA sobre quais atividades complementares fazer,
ponderando aprendizado e interesse, também é uma boa estratégia.

<b>Lembretes:</b>
- “Guiar o leitor” não é sinônimo de “escrever um livro”. É perfeitamente possível guiar o leitor
com textos curtos e diretos. Um texto que guia o leitor é aquele que deixa claro o que será
realizado antes de realizar a tarefa e depois discute o que foi observado.
- Citações devem aparecer o mais próximo possível do local onde a informação foi apresentada
ao leitor. Ter apenas uma seção de referências sem as devidas citações no texto não é a maneira
correta de redigir um texto científico e implicará em descontos na pontuação.

## Sumário e orientações

- [Introdução](#introducao)
  - [Importando Bibliotecas](#importando-bibliotecas)
  - [Leitura do arquivo de dados](#leitura-do-arquivo-de-dados)
  - [Analisando as colunas do dataset](#analisando-as-colunas-do-dataset)
- [Tratamento e filtro de dados](#tratamento-e-filtro-de-dados)
  - [Filtrando dados - parte 2](#filtrando-dados-parte-2)
  - [Dataframes individuais de cada espécie](#dataframes-individuais-de-cada-especie)
- [Explorando os dados](#explorando-os-dados)
  - [Peso e tamanho do retropé médios](#peso-e-tamanho-do-retrope-medios)
  - [Plotando ratos por peso e tamanho do retropé](#plotando-ratos-por-peso-e-tamanho-do-retrope)
  - [Plotando dois ratos de uma vez: peso e tamanho do retropé](#plotando-dois-ratos-de-uma-vez)
- [Dataframe do modelo](#dataframe-do-modelo)
- [Entendendo o modleo knn vizinhos](#entendendo-o-modelo-knn-vizinhos)
  - [Número de vizinhos](#numero-de-vizinhos)
  - [Pesos](#pesos)
  - [Métricas de desempenho](#metricas-de-desempenho)
  - [Atributos](#atributos)
  - [Testando: qual a melhor combinação?](#testando-qual-a-melhor-combinacao)
  - [Balanceando dados](#balanceando-dados)
  - [Testando de novo: dataframe do modelo balanceado](#testando-de-novo)
- [Modelo final](#modelo-final)
- [Modelo baseline](#modelo-baseline)
- [Planos futuros](#planos-futuros)
- [Conclusões e principais aprendizados](#conclusoes)
- [Descrição do uso de IA nesse trabalho](#uso-ia)
- [Referências](#referencias)
- [Agradecimentos especiais](#agradecimentos)

### Painel de controle

Esse é o "painel de controle" da tarefa. Como na seção "Explorando ratos", muitos gráficos são plotados, o que faz com que demore muito tempo pra rodar tudo, aqui você tem a opção de ativar/desativar algumas coisas. Dentre elas, você pode escolher plotar ou não plotar os gráficos comparativos entre duas espécies de rato, plotar ou não plotar os outros gráficos, além de escolher salvar as imagens dos gráficos comparativos no seu computador ou não. Para uma experiência completa, com visualização dos gráficos discutidos, ative apenas o `plotar_comparativos` e o `plotar_graficos`. Só ative o `salvar_imagem_graficos` caso queira ter muitos .jpg de scatterplots de duas espécies de ratos diferentes.

In [1]:
plotar_comparativos = False
plotar_graficos = False
salvar_imagem_graficos = False

## <a id = "introducao"></a> Introdução

O seguinte trabalho tem como objetivo principal discutir e analisar o modelo de knn vizinhos, também conhecido como k vizinhos mais próximos, além de desenvolver um modelo de knn para a classificação de roedores entre as espécies _Peromyscys maniculatus_ e _Peromyscus eremicus_, partindo de atributos e características de indivíduos de cada espécie. Para isso, foram utilizados os dados do <b>Portal Project Teaching Database</b>, fundado pela National Science Foundation [1]. Os arquivos originais do data set podem ser acessados [aqui](https://figshare.com/articles/dataset/Portal_Project_Teaching_Database/1314459).

Para o desenvolvimento e discussão do modelo, foi utilizada a biblioteca `scikit-learn`, uma biblioteca de código aberto focada em aprendizado de máquina que oferece inúmeras ferramentas de ajuste de modelos, pré-processamento de dados, seleção de modelos, avaliação de modelos, dentre outras funcionalidades [2].

### <a id = "importando-bibliotecas"></a> Importando bibliotecas

Importa as bibliotecas que serão utilizadas e define a semente aleatória a ser utilizada durante o desenvolvimento do projeto.
- A biblioteca `pandas` é utilizada para a criação e manipulação de dataframes, que contém os dados trabalhados, além de visualizações gráficas;
- A biblioteca `random` é utilizada para a realização de experimentos pseudo-aleatórios
- A biblioteca `seaborn` é utilizada para a visualização gráfica como ferramenta para discussão de dados
- A biblioteca `matplotlib` é utilizada como suporte para as visualizações gráficas do seaborn.

In [2]:
import pandas as pd
import random as rd
import seaborn as sns
import statistics as st
import matplotlib.pyplot as plt

SEMENTE_ALEATORIA = 1225

In [3]:
import matplotlib
import sys
print("Versão do Python:        ",sys.version)
print("Versão do pandas:        ",pd.__version__)
print("Versão do seaborn:       ",sns.__version__)
print("Versão do matplotlib:    ",matplotlib.__version__)


Versão do Python:         3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)]
Versão do pandas:         2.3.3
Versão do seaborn:        0.13.2
Versão do matplotlib:     3.10.6


```
Python:        3.13.15 (random, statistics)
pandas:        2.2.3
seaborn:       0.13.2
matplotlib:    3.10.0
```

### <a id = "leitura-do-arquivo-de-dados"></a> Leitura do arquivo de dados

A primeira coisa que precisamos fazer é realizar a leitura do arquivo que vamos utilizar. Utilizamos o método `pd.read_csv()` para ler o arquivo `combined.csv`, que contém todos os dados com os quais iremos trabalhar. Você pode ver que há duas células para a leitura do notebook: A primeira é caso você esteja utilizando o Google Colab e tenha o arquivo `combined.csv` na sua pasta do google drive. A segunda é a que você deve utilizar caso esteja rodando esse notebook localmente. <b>Lembre-se de ter o arquivo `combined.csv` na mesma pasta que esse notebook.</b>

In [4]:
# # essa célula é para ser utilizada no google colab, tendo o arquivo combined.csv em seu google drive.
# # não ter carregador do notebook te leva a medidas desesperadas.

# from google.colab import drive
# drive.mount('/content/drive')

# df = pd.read_csv('/content/drive/My Drive/combined.csv')
# df

In [5]:
# essa célula deve ser utilizada caso você esteja rodando localmente, com o notebook na mesma pasta que o arquivo combined.csv

# define o nome do arquivo que vamos ler
arquivo = "combined.csv"

# lê o arquivo
df = pd.read_csv(arquivo, sep=",", header=None)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
1,1,7,16,1977,2,NL,M,32,NaN,Neotoma,albigula,Rodent,Control
2,72,8,19,1977,2,NL,M,31,NaN,Neotoma,albigula,Rodent,Control
3,224,9,13,1977,2,NL,NaN,NaN,NaN,Neotoma,albigula,Rodent,Control
4,266,10,16,1977,2,NL,NaN,NaN,NaN,Neotoma,albigula,Rodent,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34782,26966,10,25,1997,7,PL,M,20,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34783,27185,11,22,1997,7,PL,F,21,22,Peromyscus,leucopus,Rodent,Rodent Exclosure
34784,27792,5,2,1998,7,PL,F,20,8,Peromyscus,leucopus,Rodent,Rodent Exclosure
34785,28806,11,21,1998,7,PX,NaN,NaN,NaN,Chaetodipus,sp.,Rodent,Rodent Exclosure


### <a id = "analisando-as-colunas-do-dataset"></a>Analisando as colunas do dataset

Esse dataset apresenta 13 colunas, ou seja, 13 atributos diferentes para descrever os indivíduos que foram registrados no dataset. A seguir, vamos ver mais sobre o que cada uma dessas colunas representa. As informações apresentadas abaixo foram retiradas da documentação do pacote <b>ratdat</b>. [3]

- <b>`record_id:`</b> Identificador de registro único, como um "CPF" do rato
- <b>`month:`</b> Mês em que a captura foi realizada; Categórico
- <b>`day:`</b> Dia em que a captura foi realizada; Categórico
- <b>`year:`</b> Ano em que a captura foi realizada; Categórico
- <b>`plot_id:`</b> Plot em que o indivíduo foi capturado; Categórico
- <b>`species_id:`</b> Identificação da espécie, organizado pela inicial do gênero e inicial da espécie; Categórico
- <b>`sex:`</b> Sexo do indivíduo; Categórico
- <b>`hindfoor_length:`</b> Medida do retropé do indivíduo, em milímetros (mm); Numérico
- <b>`weight:`</b> Peso do indivíduo, registrado em gramas (g); Numérico
- <b>`genus:`</b> Gênero da espécie do indivíduo; Categórico
- <b>`species:`</b> Nome em latim da espécie do indivíduo; Categórico
- <b>`taxa:`</b> Categorial taxonômica geral da espécie do indivíduo; Categórico
- <b>`plot_type:`</b> Tipo de manipulação experimental conduzida no plot (plot_id) do indivíduo; Categórico</b>

Nesses dados, o termo `plot` refere-se a um local físico específico ou quadrante experimental no deserto onde são realizadas a captura de roedores e a monitorização das espécies. Para a coluna `plot_type`, temos as seguintes possíveis classificações:

- `Control:` Parcela de controle do experimento, ou seja, sem nenhuma manipulaçõa.
- `Rodent Exclosure:` Bloqueia o acesso de roedores àquela área em específico.
- `Long-term Krat Exclosure:` Bloqueia o acesso dos ratos-cangurus (Krat - abreviação de kangooro rat) àquela área, a longo prazo. Os ratos-cangurus são os roedores do gênero Dipodomys.
- `Short-term Krat Exclosure:` Bloqueia o acesso dos ratos-cangurus àquela área, a curto prazo.
- `Spectab Exclosure:` Bloqueia o acesso da espécie <i>Dipodomys spectabilis</i> àquela área em específico.

## <a id = "tratamento-e-filtro-de-dados"></a> Tratamento e filtro de dados

Agora que lemos o arquivo e o armazenamos em um objeto de data frame, precisamos tratar e filtrar os dados que obtemos. A primeira coisa que podemos perceber quando exibimos o data frame é que as colunas estão identificadas por <b>índices numéricos</b>, e não por o que elas representam. Por outro lado, as colunas estão identificadas estão na primeira linha do data frame, como podemos observar na célula abaixo:

In [6]:
# .iloc[indice] -> imprime uma linha do data frame, dado seu indice
print(df.iloc[0])

0           record_id
1               month
2                 day
3                year
4             plot_id
5          species_id
6                 sex
7     hindfoot_length
8              weight
9               genus
10            species
11               taxa
12          plot_type
Name: 0, dtype: object


Com isso em vista, e também consdierando a documentação do dataset que estamos trabalhando, vamos renomear as colunas de acordo com o que elas representam. Para isso, utilizamoso método `.rename()`. Vamos aproveitar e remover a primeira linha do data frame, já que ela só continha os nomes de cada uma das colunas. Para isso, utilizamos o método `.drop()`:

In [7]:
# renomeia as colunas do data frame com base no index
df = df.rename(columns={0: 'record_id',
                        1: 'month',
                        2: 'day',
                        3: 'year',
                        4: 'plot_id',
                        5: 'species_id',
                        6: 'sex',
                        7: 'hindfoot_length',
                        8: 'weight',
                        9: 'genus',
                        10: 'species',
                        11: 'taxa',
                        12: 'plot_type'
                  })
# remove a primeira linha pelo index
df = df.drop( index = 0 )

Agora, se nós exibirmos o data frame novamente, podemos observar que as colunas estão com seus novos nomes e que a primeira linha não é mais dos nomes das colunas:

In [8]:
df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
1,1,7,16,1977,2,NL,M,32,NaN,Neotoma,albigula,Rodent,Control
2,72,8,19,1977,2,NL,M,31,NaN,Neotoma,albigula,Rodent,Control
3,224,9,13,1977,2,NL,NaN,NaN,NaN,Neotoma,albigula,Rodent,Control
4,266,10,16,1977,2,NL,NaN,NaN,NaN,Neotoma,albigula,Rodent,Control
5,349,11,12,1977,2,NL,NaN,NaN,NaN,Neotoma,albigula,Rodent,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34782,26966,10,25,1997,7,PL,M,20,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34783,27185,11,22,1997,7,PL,F,21,22,Peromyscus,leucopus,Rodent,Rodent Exclosure
34784,27792,5,2,1998,7,PL,F,20,8,Peromyscus,leucopus,Rodent,Rodent Exclosure
34785,28806,11,21,1998,7,PX,NaN,NaN,NaN,Chaetodipus,sp.,Rodent,Rodent Exclosure


O próximo passo é remover as linhas que tiverem alguma informação faltando, já que não queremos que nenhum dado esteja faltando quando formos trabalhar com eles. Para isso, vamos utilizar o método `.dropna()`:

In [9]:
# remove linhas que tenham informações faltando
df = df.dropna()
df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
12,845,5,6,1978,2,NL,M,32,204,Neotoma,albigula,Rodent,Control
14,1164,8,5,1978,2,NL,M,34,199,Neotoma,albigula,Rodent,Control
15,1261,9,4,1978,2,NL,M,32,197,Neotoma,albigula,Rodent,Control
18,1756,4,29,1979,2,NL,M,33,166,Neotoma,albigula,Rodent,Control
19,1818,5,30,1979,2,NL,M,32,184,Neotoma,albigula,Rodent,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34780,26557,7,29,1997,7,PL,F,20,22,Peromyscus,leucopus,Rodent,Rodent Exclosure
34781,26787,9,27,1997,7,PL,F,21,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34782,26966,10,25,1997,7,PL,M,20,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34783,27185,11,22,1997,7,PL,F,21,22,Peromyscus,leucopus,Rodent,Rodent Exclosure


Podemos observar que esse passo foi fundamental para nosso tratamento de dados, já que o dataframe antes de ter as linhas com informações faltando tinha 34786 linhas, e agora, depois de ser filtrado, possui apenas 30676.

Como foi apresentado na introduçã, vamos trabalhar apenas com os roedores da tabela. Portanto, vamos filtrar o data frame para que sejam exibidas apenas as linhas cuja coluna `"taxa"` seja igual a `"Rodent"`, utilizando o método `.loc[]`:

In [10]:
# filtra para que só apareçam as linhas sobre roedores
filtro = df['taxa'] == "Rodent"
df = df.loc[filtro]
df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
12,845,5,6,1978,2,NL,M,32,204,Neotoma,albigula,Rodent,Control
14,1164,8,5,1978,2,NL,M,34,199,Neotoma,albigula,Rodent,Control
15,1261,9,4,1978,2,NL,M,32,197,Neotoma,albigula,Rodent,Control
18,1756,4,29,1979,2,NL,M,33,166,Neotoma,albigula,Rodent,Control
19,1818,5,30,1979,2,NL,M,32,184,Neotoma,albigula,Rodent,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34780,26557,7,29,1997,7,PL,F,20,22,Peromyscus,leucopus,Rodent,Rodent Exclosure
34781,26787,9,27,1997,7,PL,F,21,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34782,26966,10,25,1997,7,PL,M,20,16,Peromyscus,leucopus,Rodent,Rodent Exclosure
34783,27185,11,22,1997,7,PL,F,21,22,Peromyscus,leucopus,Rodent,Rodent Exclosure


Diferentemente de quando removemos as linhas com informações faltando, selecionar apenas os roedores não provocou nenhuma mudança no número de linhas do data frame. Isso mostra que, infelizmente, os outros grupos taxônomicos presentes no data frame (os pássaros, répteis e o coelho) não tinham todas as suas informações na tabela original. Pobres animais não-roedores que foram negligenciados. :(

### <a id = "filtrando-dados-parte-2"></a> Filtrando dados - parte 2

Antes de decidirmos quais serão as duas espécies que vamos prever, precisamos saber quantos dados de cada uma dessas espécies existem na tabela. Para isso, vamos utilizar o método `.values_counts()` na coluna `species`, para que seja possível visualizar quantos exemplares de cada espécie de roedor ainda estão na tabela depois dos filtros anteriores.

In [11]:
# define a coluna "species" do data frame como um objeto series
serie_species = pd.Series( df["species"] )

# conta quantas vezes cada espécie aparece na tabela, e ordena em ordem decrescente por quantidade.
frequencia_species = serie_species.value_counts()
print(frequencia_species)

species
merriami        9727
penicillatus    2969
baileyi         2803
ordii           2790
megalotis       2417
torridus        2081
spectabilis     2023
flavus          1469
eremicus        1198
albigula        1045
leucogaster      905
maniculatus      835
hispidus         159
fulvescens        73
taylori           45
ochrognathus      40
fulviventer       38
leucopus          35
sp.                9
montanus           8
intermedius        7
Name: count, dtype: int64


Agora, queremos que as espécies que vamos tentar prever tenham pelo menos 150 exemplares cada uma. Antes disso, é importante comentar que a "espécie" `sp.` não representa, de fato, uma espécie, mas sim espécies que não foram identificadas e por isso receber a espécie "sp". Mas como ela não chega a ter 150 indivíduos, não há necessidade de removê-la individualmente. Voltando aos filtros: Primeiro, vamos selecionar quais são as espécies que atendem ao requisito "ter pelo menos 150 exemplares":

In [12]:
# cria uma lista que irá receber quais espécies têm no minimo 150 exemplares
especies_desejadas = []

# itera a lista de frequencia pela espécie registrada e a quantidade
for especie, quantidade in frequencia_species.items():

    # se tiver pelo pelos 150, é uma espécie desejada, entao ela entra na lista
    if quantidade >= 150:
        especies_desejadas.append( especie )

print(f"Total de espécies que atendem ao requisito de pelo menos 150 exemplares encontradas: {len(especies_desejadas)}")
for especie in especies_desejadas:
    print(f"- Espécie '{especie}' atende ao requisito. {frequencia_species[especie]} exemplares registrados")

Total de espécies que atendem ao requisito de pelo menos 150 exemplares encontradas: 13
- Espécie 'merriami' atende ao requisito. 9727 exemplares registrados
- Espécie 'penicillatus' atende ao requisito. 2969 exemplares registrados
- Espécie 'baileyi' atende ao requisito. 2803 exemplares registrados
- Espécie 'ordii' atende ao requisito. 2790 exemplares registrados
- Espécie 'megalotis' atende ao requisito. 2417 exemplares registrados
- Espécie 'torridus' atende ao requisito. 2081 exemplares registrados
- Espécie 'spectabilis' atende ao requisito. 2023 exemplares registrados
- Espécie 'flavus' atende ao requisito. 1469 exemplares registrados
- Espécie 'eremicus' atende ao requisito. 1198 exemplares registrados
- Espécie 'albigula' atende ao requisito. 1045 exemplares registrados
- Espécie 'leucogaster' atende ao requisito. 905 exemplares registrados
- Espécie 'maniculatus' atende ao requisito. 835 exemplares registrados
- Espécie 'hispidus' atende ao requisito. 159 exemplares registrad

Agora que sabemos quais espécies atendem ao novo requisito que estabelecemos, utilizamos o método `isin()` [2] para filtrar apenas as espécies que estejam dentro da lista de "espécies desejadas", junto ao método `.loc[]`.

In [13]:
filtro = df['species'].isin( especies_desejadas )
df = df.loc[filtro]
df

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
12,845,5,6,1978,2,NL,M,32,204,Neotoma,albigula,Rodent,Control
14,1164,8,5,1978,2,NL,M,34,199,Neotoma,albigula,Rodent,Control
15,1261,9,4,1978,2,NL,M,32,197,Neotoma,albigula,Rodent,Control
18,1756,4,29,1979,2,NL,M,33,166,Neotoma,albigula,Rodent,Control
19,1818,5,30,1979,2,NL,M,32,184,Neotoma,albigula,Rodent,Control
...,...,...,...,...,...,...,...,...,...,...,...,...,...
34775,32477,8,25,2001,7,PB,M,28,32,Chaetodipus,baileyi,Rodent,Rodent Exclosure
34776,33103,11,17,2001,7,PB,M,28,41,Chaetodipus,baileyi,Rodent,Rodent Exclosure
34777,33305,12,15,2001,7,PB,M,29,44,Chaetodipus,baileyi,Rodent,Rodent Exclosure
34778,34524,7,13,2002,7,PB,M,25,16,Chaetodipus,baileyi,Rodent,Rodent Exclosure


Para vizualizarmos novamente quais espécies ainda estão no data frame e quantos exemplares existem de cada uma de maneira mais clara, utilizamos o método `.value_counts()` novamente. Só pra ter certeza de que funcionou e que de fato temos apenas roedores com mais de 150 exemplates:

In [14]:
# define a coluna "species" do data frame como um objeto series
serie_species = pd.Series( df["species"] )

# conta quantas vezes cada espécie aparece na tabela, e ordena em ordem decrescente por quantidade.
frequencia_species = serie_species.value_counts()
print(frequencia_species)

species
merriami        9727
penicillatus    2969
baileyi         2803
ordii           2790
megalotis       2417
torridus        2081
spectabilis     2023
flavus          1469
eremicus        1198
albigula        1045
leucogaster      905
maniculatus      835
hispidus         159
Name: count, dtype: int64


Com isso, concluímos o nosso filtro de espécies de roedores pelo critério "ter pelo menos 150 exemplares".

### <a id = "dataframes-individuais-de-cada-especie"></a> Dataframes individuais de cada espécie

Para que seja mais fácil de trabalhar e plotar informações sobre os nossos roedores, vamos separar cada uma das espécies em um dataframe individual. Para isso, utilizaremos o método `.copy()`, para criar uma cópia independente do dataframe original, e em seguida, filtramos o dataframe para que sejam consideradas apenas as linhas onde a coluna `species` seja igual a espécie que estamos filtrando. Definimos uma função para que isso seja feito da melhor forma:

In [15]:
def dataframe_individual_especie(especie, dataframe=df):
    """Cria um dataframe separado para uma espécie em específico, com base no dataframe original"""

    # copia e filtra o dataframe original
    novo_df = df.copy()
    logica = df["species"] == especie
    novo_df = novo_df[logica]

    # ajuste
    novo_df['weight'] = pd.to_numeric(novo_df['weight'], errors='coerce').fillna(0)
    novo_df['hindfoot_length'] = pd.to_numeric(novo_df['hindfoot_length'], errors='coerce').fillna(0)

    return novo_df

As linhas que incluem o método `pd.to_numeric()` [5] existem por causa de erros que estavam acontecendo quando tentávamos fazer gráficos com os dados (veremos isso futuramente). Acredito que esses erros se deram pelo fato de que, talvez, essas colunas tivessem suas informações marcadas como tipo `string`, e não como tipo `int`, apesar de serem números. Também tentei utilizar o método `.astype(int)`, mas continuava retornando erros. Sendo assim, o `pd.to_numeric()` foi a melhor opção que encontrei. O parâmetro `errors = 'coerce'` diz que, caso exista um valor que não pode ser convertido para um número, ele deve ser substituido por `NaN`. Logo em seguida, com `.fillna(0)`, substituímos todos as instâncias de `NaN` por 0.

Mas, como já filtramos o dataframe anteriormente, é esperado que não haja nenhum dado `NaN` nos dataframes individuais.

Sendo assim, vamos criar dataframes individuais para cada uma das espécies de ratos que nós temos, utilizando da nossa mais nova função:

In [16]:
df_penicillatus = dataframe_individual_especie("penicillatus")
df_baileyi= dataframe_individual_especie("baileyi")
df_merriami = dataframe_individual_especie("merriami")
df_ordii = dataframe_individual_especie("ordii")
df_megalotis = dataframe_individual_especie("megalotis")
df_torridus = dataframe_individual_especie("torridus")
df_spectabilis = dataframe_individual_especie("spectabilis")
df_flavus = dataframe_individual_especie("flavus")
df_eremicus = dataframe_individual_especie("eremicus")
df_albigula = dataframe_individual_especie("albigula")
df_leucogaster = dataframe_individual_especie("leucogaster")
df_maniculatus = dataframe_individual_especie("maniculatus")
df_hispidus = dataframe_individual_especie("hispidus")

## <a id = "explorando-os-dados"></a> Explorando os dados

Antes de escolhermos quais serão as duas espécies que serão previstas ou quais serão os atributos que iremos utilizar no nosso modelo, vamos explorar um pouco mais os atributos dos nossos roedores.

### <a id = "peso-e-tamanho-do-retrope-medios"></a> Peso e tamanho do retropé médios

A próxima coisa que vamos calcular é a média do peso e do tamanho de retropé de cada uma das espécies que selecionamos. Para isso, definimos uma função (para que o dicionário que montaremos a seguir não fique tão poluído) que retorna a média de uma coluna, arredondando o valor obtido para duas casas decimais. Em seguida, armazenamos cada uma dessas informações em um dicionário de dicionários para cada uma das espécies.

Apesar da função `media()` que criaremos a seguir parecer totalmente inútil e redundante, já que ela é bem simples, ela foi criada pois acredito que o código do dicionário de médias dos roedores estava muito poluído com `round(st.mean( df[coluna].astype(int) ), 2)` aparecendo o tempo todo. Por isso, temos uma funçãozinha pra calcular a média também, apesar dela ser bem simples.

Utilizamos o método `.astype(int)` [5] para GARANTIR que as colunas terão valores numéricos, mesmo que, supostamente, isso já tenha sido feito anteriormente. Principalmente por ser uma função que poderia ser utilizada em outros dataframes, é melhor ter muita certeza de que a coluna recebida terá valores inteiros. Essa função retorna o valor de média já arredondado para duas casas decimais.

In [17]:
def media (df, coluna):
    """Retorna a média dos valores de uma coluna de um dataframe."""
    return round(st.mean( df[coluna].astype(int) ), 2)

Agora, vamos montar nosso dicionário de medidas de peso e pezinho de ratos:

In [18]:
medias_roedores = {"merriami": {"Peso": media(df_merriami, "weight"), "Retropé": media(df_merriami, "hindfoot_length")},

                   "penicillatus":{"Peso": media(df_penicillatus, "weight"), "Retropé": media(df_penicillatus, "hindfoot_length")},

                   "baileyi":{"Peso": media(df_baileyi, "weight"), "Retropé": media(df_baileyi, "hindfoot_length")},

                   "ordii":{"Peso": media(df_ordii, "weight"), "Retropé": media(df_ordii, "hindfoot_length")},

                   "megalotis":{"Peso": media(df_megalotis, "weight"), "Retropé": media(df_megalotis, "hindfoot_length")},

                   "torridus":{"Peso": media(df_torridus, "weight"), "Retropé": media(df_torridus, "hindfoot_length")},

                   "spectabilis":{"Peso": media(df_spectabilis, "weight"), "Retropé": media(df_spectabilis, "hindfoot_length")},

                   "flavus":{"Peso": media(df_flavus, "weight"), "Retropé": media(df_flavus, "hindfoot_length")},

                   "eremicus":{"Peso": media(df_eremicus, "weight"), "Retropé": media(df_eremicus, "hindfoot_length")},

                   "albigula":{"Peso": media(df_albigula, "weight"), "Retropé": media(df_albigula, "hindfoot_length")},

                   "leucogaster":{"Peso": media(df_leucogaster, "weight"), "Retropé": media(df_leucogaster, "hindfoot_length")},

                   "maniculatus":{"Peso": media(df_maniculatus, "weight"), "Retropé": media(df_maniculatus, "hindfoot_length")},

                   "hispidus":{"Peso": media(df_hispidus, "weight"), "Retropé": media(df_hispidus, "hindfoot_length")},
                  }

for roedor in medias_roedores:
    print(f"{roedor}: {medias_roedores[roedor]}")

merriami: {'Peso': 43.14, 'Retropé': 35.99}
penicillatus: {'Peso': 17.19, 'Retropé': 21.75}
baileyi: {'Peso': 31.74, 'Retropé': 26.11}
ordii: {'Peso': 48.87, 'Retropé': 35.59}
megalotis: {'Peso': 10.58, 'Retropé': 16.45}
torridus: {'Peso': 24.22, 'Retropé': 20.27}
spectabilis: {'Peso': 120.23, 'Retropé': 49.99}
flavus: {'Peso': 7.96, 'Retropé': 15.58}
eremicus: {'Peso': 21.58, 'Retropé': 20.2}
albigula: {'Peso': 158.78, 'Retropé': 32.25}
leucogaster: {'Peso': 31.33, 'Retropé': 20.53}
maniculatus: {'Peso': 21.34, 'Retropé': 20.43}
hispidus: {'Peso': 64.85, 'Retropé': 28.05}


A partir dessas medidas, começamos a notar coisas interessantes. A menor espécie que temos é a espécie <i>Perognathus flavus</i>, cujo peso médio é de aproximadamente 8 gramas (aproximadamente o peso de um quadradinho de chocolate de uma barra de chocolate convencional). Por outro lado, a maior espécie é o <i>Neotoma albigula</i>, pesando 158 gramas (aproximadamente o peso de uma barra de sabonete tamanho família). A espécie com a menor medida de retropé média também é a <i>Perognathus flavus</i>, com um pezinho de 15.5 milímetros, ou 1,5 cm (mais ou menos a grossura de um dedinho). A espécie com o maior pezinho médio de todas é a <i>Dipodomys spectabilis</i>, com quase 5 centímetros de pé (mais ou menos o comprimento de uma pilha AA). Por essas informações, já conseguimos ter uma ideia do tamanho dessas espécies - mas e se fosse possível visualizar isso de uma forma mais clara? Mais... _gráfica_?

### <a id = "plotando-ratos-por-peso-e-tamanho-do-retrope"></a> Plotando ratos por peso e tamanho do retropé

Para vizualizarmos melhor a relação entre a medida de retropé e de peso das espécies de ratos que estamos trabalhando, vamos plotar gráficos de dispersão do tamanho de retropé e do peso para cada uma das nossas 13 espécies.

#### Definindo funções

Primeiro, vamos definir a função `plotar_grafico()`, para facilitar nossa vida. Ela recebe o `dataframe` a ser analisado e as duas colunas que vamos plotar, como `eixoX` e `eixoY`, respectivamente. O parâmetro `pos_legenda` é opcional e serve para trocar a posição do bloquinho de legendas do gráfico, para evitar que ele fique na frente de muitas informações importantes (é meio inevitável que ele cubra algum ponto, mas antes cobrir só um ponto do que cobrir 30 pontos).

Essa função também utiliza os métodos `.axvline()` e `.axhline()` para adicionar uma linha vertical e uma horizontal, representando as médias dos valores do eixo x e do eixo y, respectivamente. Também definimos um título padrão para esse tipo de gráfico e setamos as legendas de cada eixo como o nome da coluna que é plotada naquele eixo.

In [19]:
def plotar_grafico(dataframe, eixoX, eixoY, pos_legenda = 2):
  """Plota um gráfico scatterplot da distribuição entre o eixoX e o eixoY"""

  # pega o nome e genero da especie plotada, para o titulo do grafico.
  genero = dataframe["genus"].iloc[0]
  especie = dataframe["species"].iloc[0]

    # conta os pontos de mesma posiçõa, para apresentarmos a densidade dos pontos no gráfico
  contagens = (
        dataframe
        .groupby([eixoX, eixoY])
        .size()
        .reset_index(name = "contagem")
    )

    # plota o gráfico
  eixo = sns.scatterplot(
        #marker = "*",
        data = contagens,
        x = eixoX,
        y = eixoY,
        hue = "contagem",
        size = "contagem",
        palette = "flare",
    )

  # plota linhas com o valor de média dos valores dos eixos X e Y
  eixo.axvline( media(dataframe, eixoX), linestyle = "--", color = "red", label = ("Média de " + str(eixoX) + ": " + str(media(dataframe, eixoX))))
  eixo.axhline( media(dataframe, eixoY), linestyle = "-", color = "blue", label = ("Média de "+ str(eixoY)) + ": " + str(media(dataframe, eixoY)))

  #titulo
  titulo = f"Plotagem de {eixoX} e {eixoY} da espécie {genero} {especie}"
  eixo.set_title( titulo )

  #legendas
  eixo.set_xlabel(eixoX)
  eixo.set_ylabel(eixoY)
  eixo.legend(loc = pos_legenda,
                framealpha = 0.15,
                facecolor = "purple"
               )

#### Scatterplot entre peso e retropé da espécie <i>Chaetodipus baileyi</i>

A primeira espécie que vamos analisar é a espécie <i>C. baileyi</i>. Lembrande que `weight` representa o peso dos ratinhos e o `hindfoot_lenght` representa o peso dos ratinhos:

In [20]:
if plotar_graficos:
  plotar_grafico(df_baileyi, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Para discutirmos melhor as informações, vamos calcular também os valores mínimos e máximos para as medidas de pé e de peso:

In [21]:
print(f"Quantidade de indivíduos: { len(df_baileyi["weight"])}")
print()
print(f"Peso mínimo: { min(df_baileyi["weight"])}g")
print(f"Peso máximo: { max(df_baileyi["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_baileyi["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_baileyi["hindfoot_length"])}mm")

Quantidade de indivíduos: 2803

Peso mínimo: 12g
Peso máximo: 55g

Retropé mínimo: 2mm
Retropé máximo: 47mm


Podemos observar que os ratinhos <i>C. baileyi</i> apresentam um peso bem variado, entre 12 e 55 gramas. O tamanho do pezinho também é bastante variado, entre 2 e 47mm. Porém, se observarmos no gráfico, percebemos que esse pezinho de 2mm está bem fora do padrão de tamanho de retropé esperado, e o mesmo acontece para o retropé medindo 47mm. Porém, não temos como saber se esses ratos foram catalogados de maneira equivocada (como um erro de digitação dos valores das medidas) ou se são apenas ratos com pezinhos minúsculos ou pés enormes, então não vamos eliminar esses dados. No entanto, se considerarmos os valores mais comuns dessas medidas, obtemos retropés entre aproximadamente 17mm e 36mm.

Também é possível observar um sutil aumento do tamanho do retropé conforme o peso aumenta. Para analisar isso, vamos calcular a <b>correlação de Pearson</b> entre o peso e o tamanho do retropé:

In [22]:
pearson = st.correlation(df_baileyi["weight"], df_baileyi["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (C. baileyi): {pearson}")

Correlação de Pearson entre peso e retropé (C. baileyi): 0.3160589966049329


O valor obtido foi de 0.3 para a correlação entre tamanho do retropé e peso dos ratinhos da espécie <i>C. baileyi</i>, o que demosntra que há uma correlação positiva entre as duas medidas [6], ou seja, quando uma aumenta, a outra também aumenta. Nesse caso, seria que quanto maior o peso, maior o pezinho do rato. No entanto, esse valor obtido é considerado como uma evidência fraca, já que não é tão próximo de 1.

#### Scatterplot entre peso e retropé da espécie <i>Chaetodipus penicillatus</i>

A próxima espécie que vamos analisar é a <i>C. penicillatus</i>.

In [23]:
if plotar_graficos:
  plotar_grafico(df_penicillatus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 1)

Calculando os valores de mínimo e máximo de cada eixo:

In [24]:
print(f"Quantidade de indivíduos: { len(df_penicillatus["weight"])}")
print()
print(f"Peso mínimo: { min(df_penicillatus["weight"])}g")
print(f"Peso máximo: { max(df_penicillatus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_penicillatus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_penicillatus["hindfoot_length"])}mm")

Quantidade de indivíduos: 2969

Peso mínimo: 4g
Peso máximo: 74g

Retropé mínimo: 11mm
Retropé máximo: 41mm


Primeiro, podemos observar que as medidas de peso estão bem mais concentradas do que estavam na espécie que analisamos anteriormente, com pesos que ficam, em sua maioria, entre 4 e 40 gramas. Porém, algo que chega a ser até engraçado é que existe um único ratinho que pesa 74 gramas, que é o rato mais pesado dessa espécie. Não temos como saber o que aconteceu com esse dado, ou com esse rato, para ele ser tão distoante assim. Considerando que a média é de 17.2 gramas, aproximadamente, esse rato é aproximadamente 4,3 vezes maior do que um ratinho médio de mesma espécie.

Algo semelhante acontece nas medidas de tamanho de pé: temos ratinhos com pés, em sua maioria, entre 11 e 26 mm, enquanto existe um único rato cujo pezinho mede 41 mm. Também não sabemos o que houve com esse dado, ou com esse ratinho. Considerando a média de 21.75mm do retropé dessa espécie, o pé desse rato mede quase o dobro da média. Tudo o que podemos dizer é que, de acordo com esse dataset, existe um ratinho muito massudo e um ratinho muito pezudo na espécie <i>C. penicillatus</i>.

Também é interessante observar como a maior concentação de ratos acontece exatamente onde as duas linhas de médias plotadas se cruzam. Como podemos observar um leve crescimento do tamanho do pé conforme o aumento do peso, vamos calcular a Correlação de Pearson mais uma vez:

In [25]:
pearson = st.correlation(df_penicillatus["weight"], df_penicillatus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (penicillatus): {pearson}")

Correlação de Pearson entre peso e retropé (penicillatus): 0.2629904309169442


O coeficiente de Pearson calculado foi de 0.26, o que indica uma correlação positiva, mas também é considerada evidência fraca.

#### Scatterplot entre peso e retropé da espécie <i>Dipodomys merriami</i>

A próxima espécie que vamos analisar é a <i>D. merriami</i>.

In [26]:
if plotar_graficos:
  plotar_grafico(df_merriami, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 4)

Calculando os valores de mínimo e máximo de cada eixo:

In [27]:
print(f"Quantidade de indivíduos: { len(df_merriami["weight"])}")
print()
print(f"Peso mínimo: { min(df_merriami["weight"])}g")
print(f"Peso máximo: { max(df_merriami["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_merriami["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_merriami["hindfoot_length"])}mm")

Quantidade de indivíduos: 9727

Peso mínimo: 10g
Peso máximo: 65g

Retropé mínimo: 16mm
Retropé máximo: 50mm


Ao contrário do que aconteceu anteriormente, aqui não temos nenhum caso de um rato anormalmente pesado ou pezudo, mas sim de um ratinho bem menor do que a média. Pelo menos esse rato em específico é pequeno tanto em pé, quanto em peso, com 16mm e 10g, respectivamente. Dada a existência de outros ratinhos menores, podemos supor que, talvez, esses ratinhos sejam ratinhos mais jovens, e por isso são menores. No entanto, ressalto que isso é só uma hipótese baseada em achismos, e que não há como comprovar que esses ratos pequenos são ratos jovens, ou se são apenas pequenos, ou se são erros de classificação, ainda mais considerando a existência de alguns ratos com medidas de peso baixas (em torno de 15 gramas) mas com medidas de retropé bem próximas a média.

Também existem 10 ratos que apresentam uma medida de retropé bem maior do que os demais ratos, mas também não temos como saber o porquê disso. Vamos apenas assumir que alguns ratos possuem pezinhos maiores do que seus outros companheiros ratos de mesma espécie. Aqui, a maior concentração de ratos também se encontra onde as duas linhas de média se cruzam.

Assim como fizemos anteriormente, vamos calcular o coeficiente de correlação de Pearson para essa espécie:

In [28]:
pearson = st.correlation(df_merriami["weight"], df_merriami["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (merriami): {pearson}")

Correlação de Pearson entre peso e retropé (merriami): 0.35737190742641944


O valaor do coeficiente calculado é de 0.35, o que indica uma correlação positiva fraca.

#### Scatterplot entre peso e retropé da espécie <i>Dipodomys ordii</i>

A próxima espécie que vamos analisar é a <i>D. ordii</i>.

In [29]:
if plotar_graficos:
  plotar_grafico(df_ordii, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Calculando os valores de mínimo e máximo de cada eixo:

In [30]:
print(f"Quantidade de indivíduos: { len(df_ordii["weight"])}")
print()
print(f"Peso mínimo: { min(df_ordii["weight"])}g")
print(f"Peso máximo: { max(df_ordii["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_ordii["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_ordii["hindfoot_length"])}mm")

Quantidade de indivíduos: 2790

Peso mínimo: 12g
Peso máximo: 76g

Retropé mínimo: 26mm
Retropé máximo: 64mm


Para os <i>D. ordii</i>, observamos que os pesos dos ratinhos estão entre 12 e 76 gramas. Os pesos não apresentam nenhum valor que possa ser estranho - claro, existem ratinhos mais leves e ratinhos mais pesados, mas em nenhum dos casos eles estão muito fora da maior concentração. As medidas de retropé, por outro lado, apresentam valores enntre 26 e 64 mm, e é aqui que as coisas parecem estranhas de novo. A maior medida de retropé, 64mm (ficou atrás da legenda, mas ainda é possível ver), aparenta estar bem fora dos demais valores, que ficam entre 26 e 39mm, aproximadamente.

Calculando o coeficiente da correlação de Pearson, temos:

In [31]:
pearson = st.correlation(df_ordii["weight"], df_ordii["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (ordii): {pearson}")

Correlação de Pearson entre peso e retropé (ordii): 0.23785877910104145


O valor calculado foi de 0.23, o que indica uma correlação positiva, mas também é considerada evidência fraca.

#### Scatterplot entre peso e retropé da espécie <i>Dipodomys spectabilis</i>

A próxima espécie que vamos analisar é a <i>D. spectabilis</i>.

In [32]:
if plotar_graficos:
  plotar_grafico(df_spectabilis, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Calculando os valores de mínimo e máximo de cada eixo:

In [33]:
print(f"Quantidade de indivíduos: { len(df_spectabilis["weight"])}")
print()
print(f"Peso mínimo: { min(df_spectabilis["weight"])}g")
print(f"Peso máximo: { max(df_spectabilis["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_spectabilis["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_spectabilis["hindfoot_length"])}mm")

Quantidade de indivíduos: 2023

Peso mínimo: 12g
Peso máximo: 190g

Retropé mínimo: 39mm
Retropé máximo: 58mm


Podemos observar que essa é a espécie com a maior variância de peso até então, indo de 12 a 190 gramas. Apesar de existirem alguns valores mais distantes do que os outros, podemos dizer que essa é a espécie com dados mais coerentes até então, já que mesmo as medidas de retropé que estão mais distantes das demais, ainda são valores coerentes, com pouca variação. As medidas de retropé ficam entre 39 e 58 mm. Também podemos observar claramente que as duas medidas analisadas aumentam juntas, o que nos leva a imaginar que o coeficiente de correlação de Pearson dessa espécie será mais alto do que os anteriores. Vamos calculá-lo para termos certeza:

In [34]:
pearson = st.correlation(df_spectabilis["weight"], df_spectabilis["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (ordii): {pearson}")

Correlação de Pearson entre peso e retropé (ordii): 0.4754936407567737


Com a medida de sendo de 0.47, a correlação é considerada positiva e podemos dizer que há uma evidência considerada moderada para essa situação.

#### Scatterplot entre peso e retropé da espécie <i>Neotoma albigula</i>

A próxima espécie que vamos analisar é a <i>N. albigula</i>.

In [35]:
if plotar_graficos:
  plotar_grafico(df_albigula, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 4)

Calculando os valores de mínimo e máximo de cada eixo:

In [36]:
print(f"Quantidade de indivíduos: { len(df_albigula["weight"])}")
print()
print(f"Peso mínimo: { min(df_albigula["weight"])}g")
print(f"Peso máximo: { max(df_albigula["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_albigula["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_albigula["hindfoot_length"])}mm")

Quantidade de indivíduos: 1045

Peso mínimo: 30g
Peso máximo: 280g

Retropé mínimo: 21mm
Retropé máximo: 42mm


Podemos observar que a variância do peso dos <i>N. albigula</i> é maior do que a dos <i>D. spectabilis</i>, com pesos entre 30 e 280 gramas. O tamanho do pezinho varia com valores entre 21 e 42 mm. Não há muitos valores que podemos considerar estranhos, com exceção de um trio de ratos com pezinhos de 21mm e um rato com um pezão de 42mm. Podemos observar que é a espécie, até então, que menos repete ratos que tenham o mesmo peso e medida de retropé, o que provavelmente é resultado do menor volume de dados (1045 exemplares). Também é possível perceber que existe um pequeno conjunto das duas variáveis. Novamente, vamos verificar o coeficiente de correlação de Pearson:

In [37]:
pearson = st.correlation(df_albigula["weight"], df_albigula["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (ordii): {pearson}")

Correlação de Pearson entre peso e retropé (ordii): 0.40560105768569965


O valor de 0.4 indica uma correlação positiva e moderada.

#### Scatterplot entre peso e retropé da espécie <i>Onychomys torridus</i>

A próxima espécie que vamos analisar é a <i>O. torridus</i>.

In [38]:
if plotar_graficos:
  plotar_grafico(df_torridus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Calculando os valores de mínimo e máximo de cada eixo:

In [39]:
print(f"Quantidade de indivíduos: { len(df_torridus["weight"])}")
print()
print(f"Peso mínimo: { min(df_torridus["weight"])}g")
print(f"Peso máximo: { max(df_torridus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_torridus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_torridus["hindfoot_length"])}mm")

Quantidade de indivíduos: 2081

Peso mínimo: 5g
Peso máximo: 46g

Retropé mínimo: 13mm
Retropé máximo: 50mm


Os ratos da espécie <i>O. torridus</i> apresentam pesos entre 5 e 46 gramas. Apesar de serem valores bem variados, nenhum deles aparece totalmente isolado dos demais. As medidas de retropé, por outro lado, ficam entre 13 e 50mm. Porém, a média de medida de retropé é de 20mm, e existe um único rato cujo retropé tem medida de 50mm. Mais uma vez, encontramos um rato bem pezudo. As linhas de média se cruzam onde há maior densidade de ratos, e, olhando, não é possível enxergar muito bem se os dados estão aumentando juntos. Vamos verificar isso com o coeficiente de correlação de Pearson.

In [40]:
pearson = st.correlation(df_torridus["weight"], df_torridus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (torridus): {pearson}")

Correlação de Pearson entre peso e retropé (torridus): 0.14188925690950147


O valor de 0.14 para o coeficiente de correlação de Pearson apresenta uma correlação positiva, mas seu valor é tão próximo de zero que pode ser desconsiderado.

#### Scatterplot entre peso e retropé da espécie <i>Onychomys leucogaster</i>

A próxima espécie que vamos analisar é a <i>O. leucogaster</i>.

In [41]:
if plotar_graficos:
  plotar_grafico(df_leucogaster, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 1)

Calculando os valores de mínimo e máximo de cada eixo:

In [42]:
print(f"Quantidade de indivíduos: { len(df_leucogaster["weight"])}")
print()
print(f"Peso mínimo: { min(df_leucogaster["weight"])}g")
print(f"Peso máximo: { max(df_leucogaster["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_leucogaster["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_leucogaster["hindfoot_length"])}mm")

Quantidade de indivíduos: 905

Peso mínimo: 10g
Peso máximo: 56g

Retropé mínimo: 12mm
Retropé máximo: 39mm


Os ratinhos <i>O. leucogaster</i> apresentam pesos entre 10 e 56 gramas. Nenhum deles aparenta ser muito diferente dos demais, estando com pesos bem concentrados. As medidas de retropé, por outro lado, aparentam ser bem estranhas. Elas ficam entre 12 e 39 mm, mas o rato cujo pé mede 39mm se mostra bem longe dos demais ratinhos, apesar de existirem outros 3 ratinhos de pés grandes. Diferentemente dos outros gráficos que analisamos, aqui não há apenas um ou dois pontos com as maiores densidades, deixando-as mais bem distribuídas ao redor dos eixos de peso e retropé médios que plotamos. Assim como nos seus irmãos de gênero, não conseguimos observar um aumento coeso entre as duas variáveis, então, vamos calcular o coeficiente de Pearson para eles:

In [43]:
pearson = st.correlation(df_leucogaster["weight"], df_leucogaster["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (leucogaster): {pearson}")

Correlação de Pearson entre peso e retropé (leucogaster): 0.18967230586007147


O valor de 0.18 para o coeficiente de correlação de Pearson apresenta uma correlação positiva, mas seu valor é tão próximo de zero que pode ser desconsiderado.

#### Scatterplot entre peso e retropé da espécie <i>Peromyscus eremicus</i>

A próxima espécie que vamos analisar é a <i>P. eremicus</i>.

In [44]:
if plotar_graficos:
  plotar_grafico(df_eremicus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 1)

Calculando os valores de mínimo e máximo de cada eixo:

In [45]:
print(f"Quantidade de indivíduos: { len(df_eremicus["weight"])}")
print()
print(f"Peso mínimo: { min(df_eremicus["weight"])}g")
print(f"Peso máximo: { max(df_eremicus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_eremicus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_eremicus["hindfoot_length"])}mm")

Quantidade de indivíduos: 1198

Peso mínimo: 8g
Peso máximo: 40g

Retropé mínimo: 11mm
Retropé máximo: 30mm


Os pesos dos ratinhos dessa espécie ficam entre 8 e 40 gramas. Apesar de parecer que alguns ratinhos são bem menores do que a maioria, podemos considerar que esses valores são coerentes, já que em alguns casos, eles pesam pouco e tem um pezinho pequeno também. Para não perder o costume, também temos um rato que é bem mais pezudo do que seus amiguinhos ratos de mesma espécie, com uma medida de retropé de 30mm. As linhas de média se cruzam onde há maior concentação de indivíduos com aquelas medidas de pé e de peso. Por fim, vamos plotar o coeficiente de correlação de Pearson para observar se há crescimento conjunto significativo:

In [46]:
pearson = st.correlation(df_eremicus["weight"], df_eremicus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (eremicus): {pearson}")

Correlação de Pearson entre peso e retropé (eremicus): 0.23975777758561387


O valor calculado foi de 0.23, o que indica uma correlação positiva, mas também é considerado evidência fraca.

#### Scatterplot entre peso e retropé da espécie <i>Perognathus flavus</i>

A próxima espécie que vamos analisar é a <i>P. flavus</i>.

In [47]:
if plotar_graficos:
  plotar_grafico(df_flavus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 1)

Calculando os valores de mínimo e máximo de cada eixo:

In [48]:
print(f"Quantidade de indivíduos: { len(df_flavus["weight"])}")
print()
print(f"Peso mínimo: { min(df_flavus["weight"])}g")
print(f"Peso máximo: { max(df_flavus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_flavus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_flavus["hindfoot_length"])}mm")

Quantidade de indivíduos: 1469

Peso mínimo: 4g
Peso máximo: 25g

Retropé mínimo: 7mm
Retropé máximo: 38mm


Os ratinhos <i>P. flavus</i> são, de longe, os mais levinhos das nossas análises. Seus pesos se encontram entre 4 e 25 gramas. Porém, é interessante observar como quase todos os ratos ficam concentrados na região entre 4 e 13 gramas, e de repente temos cinco ratos com pesos que são quase três vezes maiores do que a média. E provando mais uma vez que os ratos de pé grande são muitos, temos um único rato cujo retropé mede 38mm. O que é bem inusitado, considerando a média de 15mm nessa espécie. Os ratos pezudos estão em todos os lugares.

Também vamos plotar o coeficiente de correlação de Pearson para essa espécie:

In [49]:
pearson = st.correlation(df_flavus["weight"], df_flavus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (flavus): {pearson}")

Correlação de Pearson entre peso e retropé (flavus): 0.20775450992351793


O valor calculado foi de 0.2, o que indica uma correlação positiva, mas também é considerado evidência fraca.

#### Scatterplot entre peso e retropé da espécie <i>Sigmodon hispidus</i>

A próxima espécie que vamos analisar é a <i>S. hispidus</i>.

In [50]:
if plotar_graficos:
  plotar_grafico(df_hispidus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Calculando os valores de mínimo e máximo de cada eixo:

In [51]:
print(f"Quantidade de indivíduos: { len(df_hispidus["weight"])}")
print()
print(f"Peso mínimo: { min(df_hispidus["weight"])}g")
print(f"Peso máximo: { max(df_hispidus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_hispidus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_hispidus["hindfoot_length"])}mm")

Quantidade de indivíduos: 159

Peso mínimo: 16g
Peso máximo: 140g

Retropé mínimo: 20mm
Retropé máximo: 39mm


A primeira coisa que nos chama a atenção quando olhamos para esse gráfico é: existem poucos "ratos repetidos", por assim dizer. Em outras palavras, existem poucos indivíduos diferentes que apresentem as mesmas medidas de retropé e peso, ou seja, pontos que ocupam a mesma posição no scatterplot. Isso faz com que o gráfico fique horroroso, com pontinhos laranja pequenininhos e, de repente, grandes bolotas roxas horríveis. No entanto, não podemos culpar os pobres <i>S. hispidus</i> por isso - na realidade, acredito que o principal "culpado" por essa representação tenebrosa seja o baixo volume de dados existentes para essa espécie. Todas as outras espécies que analisamos apresentam mais de 800 exemplares, enquanto os pobres <i>S. hispidus</i> são apenas 159, o que interfere nas análises desenvolvidas. Por outro lado, algo que pode ser facilmente visualizado para essa espécie é como o peso e o retropé aparentam aumentar juntos. Mais uma vez, vamos calcular o Coeficiente de Correlação de Pearson e verificar:

In [52]:
pearson = st.correlation(df_hispidus["weight"], df_hispidus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (hispidus): {pearson}")

Correlação de Pearson entre peso e retropé (hispidus): 0.6060990880788444


A medida obtida de 0.6 demonstra que, de fato, os ratos mais pesados tendem a ter pés maiores.

#### Scatterplot entre peso e retropé da espécie <i>Peromyscus maniculatus</i>

A próxima espécie que vamos analisar é a <i>P. maniculatus</i>.

In [53]:
if plotar_graficos:
  plotar_grafico(df_maniculatus, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 2)

Calculando os valores de mínimo e máximo de cada eixo:

In [54]:
print(f"Quantidade de indivíduos: { len(df_maniculatus["weight"])}")
print()
print(f"Peso mínimo: { min(df_maniculatus["weight"])}g")
print(f"Peso máximo: { max(df_maniculatus["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_maniculatus["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_maniculatus["hindfoot_length"])}mm")

Quantidade de indivíduos: 835

Peso mínimo: 7g
Peso máximo: 49g

Retropé mínimo: 16mm
Retropé máximo: 36mm


A análise do gráfico dos <i>P. maniculatus</i> deveria ser uma análise super coerente, super com sentido, já que, milagrosamente, quase não temos ratinhos que fogem do padrão. Porém, o único rato diferentão compensa por todos eles. Se observarmos bem, podemos ver que existe uma única unidade, um único indivíduo, que pesa quase 50 gramas e tem um pé de 36 milímetros. Considerando a média da espécie como 20 gramas para peso e 21 milímetros de pé, esse rato definitivamente está fora do padrão esperado. Também existe um rato com aproximadamente 32mm de retropé, mas com um peso mais esperado. Desconsiderando o gigante rato massudo, os pesos dessa espécie ficam entre 7 e 36 gramas, aproximadamente. Para as medidas de pé, elas ficam em torno de 16 e 27mm. A maior concentração de ratos está exatamente onde as linhas de média se cruzam. Vamos calcular o Coeficiente de Correlação de Pearson mais uma vez:

In [55]:
pearson = st.correlation(df_maniculatus["weight"], df_maniculatus["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (maniculatus): {pearson}")

Correlação de Pearson entre peso e retropé (maniculatus): 0.30653946519939823


O valor obtido foi de 0.3, representando uma correlação positiva, mas com evidência fraca.

#### Scatterplot entre peso e retropé da espécie <i>Reithrodontomys megalotis</i>

A próxima espécie que vamos analisar é a <i>R. megalotis</i>.

In [56]:
if plotar_graficos:
  plotar_grafico(df_megalotis, eixoX = "weight", eixoY = "hindfoot_length", pos_legenda = 4)

Calculando os valores de mínimo e máximo de cada eixo:

In [57]:
print(f"Quantidade de indivíduos: { len(df_megalotis["weight"])}")
print()
print(f"Peso mínimo: { min(df_megalotis["weight"])}g")
print(f"Peso máximo: { max(df_megalotis["weight"])}g")
print()
print(f"Retropé mínimo: { min(df_megalotis["hindfoot_length"])}mm")
print(f"Retropé máximo: { max(df_megalotis["hindfoot_length"])}mm")

Quantidade de indivíduos: 2417

Peso mínimo: 4g
Peso máximo: 29g

Retropé mínimo: 6mm
Retropé máximo: 22mm


Podemos observar que os <i>R. megalotis</i> também são ratos pequeninhos, pesando entre 4 e 29 gramas. Porém, o rato que pesa 29 gramas está bem distante dos demais - desconsiderando ele, os pesos ficam entre 4 e 20 gramas. Para as medidas de pé, elas ficam entre 6 e 22mm, e embora os ratos de pé pequenininho pareçam muito distantes, eles não estão tão fora assim, com apenas alguns milímetros de diferença. Vamos calcular o coeficiente de correlação de pearson para verificar se há aumento conjunto significativo:

In [58]:
pearson = st.correlation(df_megalotis["weight"], df_megalotis["hindfoot_length"], method="linear")
print(f"Correlação de Pearson entre peso e retropé (megalotis): {pearson}")

Correlação de Pearson entre peso e retropé (megalotis): 0.15568053067625426


O valor de 0.15 para o coeficiente de correlação de Pearson apresenta uma correlação positiva, mas seu valor é tão próximo de zero que pode ser desconsiderado.

### <a id = "plotando-dois-ratos-de-uma-vez"></a> Plotando dois ratos de uma vez: peso e tamanho de retropé

Ainda precisamos decidir quais serão as espécies que vamos prever e aqui chegamos em um ponto interessante: Considerando que peso e tamanho de retropé definitivamente serão atributos utilizados na previsão, se as duas espécies que escolhermos forem muito diferentes entre si nesses dois atributos, o padrão de cada espécie pode ser identificado mais facilmente. É como se, com base no peso, pedissimos ao modelo que ele previsse se o animal é um coelhinho ou um rinoceronte: como os pesos são extremamente diferentes, o modelo raramente vai errar. Raramente esse modelo vai olhar pra um animal que pesa dois quilinhos e dizer que é um rinoceronte, assim como ele dificilmente vai olhar pra um animal de três toneladas e dizer que é um coelho - Não necessariamente por ser um modelo bom, mas sim por serem valores muito distintos.

Sendo assim, queremos que as duas espécies que vamos prever sejam minimamente parecidas em peso e tamanho do pé. Para que seja possível escolhermos uma duplinha ratônica, vamos plotar os gráficos de dispersão que plotamos anteriormente, mas agora, com duas espécies de uma vez. Vamos comparar cada espécie com todas as outras individualmente, e exibir esses gráficos em um grande painel (obrigada Leo. Sem você, eu ainda estaria plotando 78 gráficos individualmente...).

#### Definindo função

Primeiro, definimos a função `dois_ratos()`. Ela recebe os dois dataframes (das duas espécies que serão plotadas), junto com os atributos dos eixos do gráfico. Ela junta os dois dataframes recebidos em um único dataframe para a plotagem, levando em conta a espécie para a cor dos pontos.

In [59]:
def dois_ratos(df1, df2, eixoX, eixoY, pos_painel):
  """Plota um gráfico scatterplot de dois dataframes juntos, com base nos dois dataframes e nos dois eixos que serão plotados."""

  # junta os dois dataframes em um só
  dados = []
  dados = pd.concat([df1, df2])

  # define gênero e espécie das duas espécies, para colocar no titulo
  e1 = df1["species"].iloc[1]
  e2 = df2["species"].iloc[1]

  genero1 = df1["genus"].iloc[1]
  genero2 = df2["genus"].iloc[1]

    # define o titulo
  titulo = genero1 + " " + e1 + " e " + genero2 + " "+ e2

    # plota o gráfico
  grafico = sns.scatterplot(
    data = dados,
    x = eixoX,
    y = eixoY,
    ax = pos_painel, # define a posição daquele gráfico em específico no painel
    hue="species", # varia a cor dos pontos de acordo com a espécie (roxo e laranja, bem ilum 🧡💜)
    alpha = 0.2, # deixa os pontos levemente transparentes; possível ver quando duas espécies tem ratos "iguais"

    # define as cores dos pontos
    palette = {
      e1: "darkorange",
      e2: "purple"
    }
  )

  grafico.set_title(titulo)

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Chaetodipus baileyi</i>

In [60]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_baileyi, df_penicillatus, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_baileyi, df_merriami, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_baileyi, df_spectabilis, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_baileyi, df_ordii, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_baileyi, df_albigula, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_baileyi, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_baileyi, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_baileyi, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_baileyi, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_baileyi, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_baileyi, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_baileyi, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_baileyi.png",
        dpi=600,
        bbox_inches="tight"
    )

A partir dos gráficos plotados, podemos perceber que a espécie <i>Chaeetodipus Baileyi</i> não é extremamente semelhante a nenhuma das espécies que estamos analisando. Por outro lado, algo muito interessante é como os pontos se colidem mais quando plotados junto à espécie <i>Chaetodipus penicillatus</i>, que pertence ao mesmo gênero taxonômico. Também há certa semelhança com a espécie <i>Sigmodon hispidus</i>, mas, por ser a espécie com menos exemplares (159), não podemos ter certeza da semelhança entre essas duas espécies. Também é interessante ressaltar como muitas espécies apresentam a mesma faixa de peso, mas diferem no tamanho do retropé.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Chaetodipus penicillatus</i>

In [61]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_penicillatus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_penicillatus, df_merriami, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_penicillatus, df_spectabilis, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_penicillatus, df_ordii, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_penicillatus, df_albigula, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_penicillatus, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_penicillatus, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_penicillatus, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_penicillatus, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_penicillatus, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_penicillatus, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_penicillatus, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_penicillatus.png",
        dpi=600,
        bbox_inches="tight"
    )

Diferentemente da espécie dos gráficos anteriores, podemos observar que a espécie <i>Chaetodipus penicillatus</i> é semelhante em algum nível à várias das espécies, como: <i>Onychomys leucogaster, Onychomys torridus, Peromyscus eremicus</i> e <i>Peromyscus maniculatus.</i> Por outro lado, essa espécie se mostra ser totalmente diferente da espécie <i>Dipodomys spectabilis</i>, então sabemos que Chaetodipus penicillatus</i> e <i>Dipodomys spectabilis</i> não são uma dupla elegível para o nosso modelo.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Dipodomys merriami</i>

In [62]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_merriami, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_merriami, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_merriami, df_spectabilis, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_merriami, df_ordii, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_merriami, df_albigula, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_merriami, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_merriami, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_merriami, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_merriami, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_merriami, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_merriami, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_merriami, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_merriami.png",
        dpi=600,
        bbox_inches="tight"
    )

Para os <i>Dipodomys merriami</i>, a única espécie realmente semelhante é a <i>Dipodomys ordii</i>, que é do mesmo gênero filogenético. É interessante observar como a medida de retropé dessa espécie é maior do que quase todas as espécies, com exceção da <i>Dipodomys spectabillis</i>.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Dipodomys spectabilis</i>

In [63]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_spectabilis, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_spectabilis, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_spectabilis, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_spectabilis, df_ordii, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_spectabilis, df_albigula, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_spectabilis, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_spectabilis, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_spectabilis, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_spectabilis, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_spectabilis, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_spectabilis, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_spectabilis, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_spectabilis.png",
        dpi=600,
        bbox_inches="tight"
    )

Podemos perceber que os <i>Dipodomys spectabilis</i> não apresentam semelhanças com nenhuma outra espécie analisada, nem mesmo com os outros dois <i>Dipodomys</i>. Eles também têm claramente os maiores pezinhos do dataset.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Dipodomys ordii</i>

In [64]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))
  dois_ratos(df_ordii, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_ordii, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_ordii, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_ordii, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_ordii, df_albigula, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_ordii, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_ordii, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_ordii, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_ordii, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_ordii, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_ordii, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_ordii, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_ordii.png",
        dpi=600,
        bbox_inches="tight"
    )

Para a espécie <i>Dipodomys ordii</i>, a única espécie mais semelhante é a <i>Dipodomys merriami</i>, como já discutido anteriormente.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Neotoma albigula</i>

In [65]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_albigula, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_albigula, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_albigula, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_albigula, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_albigula, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_albigula, df_leucogaster, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_albigula, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_albigula, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_albigula, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_albigula, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_albigula, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_albigula, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_albigula.png",
        dpi=600,
        bbox_inches="tight"
    )

A espécie <i>Neotoma albigula</i> não apresenta nenhuma grande semelhança com nenhuma espécie. Existem pontos semelhantes com a espécie <i>Sigmodon hispidus</i>, mas como existem poucos dados dessa espécie, não podemos ter muita certeza. Também é interessante observar como espécie <i>Neotoma albigula</i> é a que apresenta o maior range de peso dentre as espécies, com pesos entre aproximadamente 40 gramas e 270 gramas.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Onychomys leucogaster</i>

In [66]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_leucogaster, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_leucogaster, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_leucogaster, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_leucogaster, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_leucogaster, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_leucogaster, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_leucogaster, df_torridus, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_leucogaster, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_leucogaster, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_leucogaster, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_leucogaster, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_leucogaster, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_leucogaster.png",
        dpi=600,
        bbox_inches="tight"
    )

Para os <i>Onychomys leucogaster</i>, notamos semelhanças com várias espécies: <i>Chaetodipus penicillatus</i>, como discutido anteriormente; <i>Onychomys torridus</i>, do mesmo genêro taxonômico; Além das duas espécies do gênero Peromyscus: <i>P. eremicus</i> e <i>P. maniculatus</i>.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Onychomys torridus</i>

In [67]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_torridus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_torridus, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_torridus, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_torridus, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_torridus, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_torridus, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_torridus, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_torridus, df_flavus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_torridus, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_torridus, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_torridus, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_torridus, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_torridus.png",
        dpi=600,
        bbox_inches="tight"
    )

Para os <i>Onychomys torridus</i>, as espécies semelhantes são praticamente as mesmas do que os <i>Onychomys leucogaster</i>: <i>C. penicillatus</i>, <i>P. eremicus</i> e <i>P. maniculatus</i>, além do próprio <i>O. leucogaster</i>. Ela também tem certa proximidade com os <i>Reithrodontomys megalotis</i>.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Perognathus flavus</i>

In [68]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_flavus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_flavus, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_flavus, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_flavus, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_flavus, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_flavus, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_flavus, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_flavus, df_torridus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_flavus, df_eremicus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_flavus, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_flavus, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_flavus, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_flavus.png",
        dpi=600,
        bbox_inches="tight"
    )

Os <i>Perognathus flavus</i> estão muito próximos das duas espécies do gênero <i>Peromyscus</i>, <i>P. eremicus</i> e <i>P. maniculatus</i>. Eles também apresentam uma forte semelhança com a espécie <i>Reithrodontomys megalotis</i>, com quase todos os pontos das duas espécies colidindo.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Peromyscus eremicus</i>

In [69]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))
  dois_ratos(df_eremicus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_eremicus, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_eremicus, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_eremicus, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_eremicus, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_eremicus, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_eremicus, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_eremicus, df_torridus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_eremicus, df_flavus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_eremicus, df_maniculatus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_eremicus, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_eremicus, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_eremicus.png",
        dpi=600,
        bbox_inches="tight"
    )

Os <i>Peromyscus eremicus</i> apresentam semelhança significativa com a espécie <i>Peromyscus maniculatus</i>, de mesmo gênero. Também apresenta semelhanças com as espécies <i>Onychomys leucogaster</i>, <i>Onychomys torridus</i> e <i>Chaetodipus penicillatus</i>, conforme discutido anteriormente.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Peromyscus maniculatus</i>

In [70]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))
  dois_ratos(df_maniculatus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_maniculatus, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_maniculatus, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_maniculatus, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_maniculatus, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_maniculatus, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_maniculatus, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_maniculatus, df_torridus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_maniculatus, df_flavus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_maniculatus, df_eremicus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_maniculatus, df_megalotis, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_maniculatus, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_maniculatus.png",
        dpi=600,
        bbox_inches="tight"
    )

Os <i>Peromyscus maniculatus</i> apresentam semelhança significativa com a espécie <i>Peromyscus eremicus</i>, de mesmo gênero. Também apresenta semelhanças com as espécies <i>Onychomys leucogaster</i>, <i>Onychomys torridus</i> e <i>Chaetodipus penicillatus</i>, conforme também discutido anteriormente.

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Reithrodontomys megalotis</i>

In [71]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_megalotis, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_megalotis, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_megalotis, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_megalotis, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_megalotis, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_megalotis, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_megalotis, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_megalotis, df_torridus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_megalotis, df_flavus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_megalotis, df_eremicus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_megalotis, df_maniculatus, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_megalotis, df_hispidus, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_megalotis.png",
        dpi=600,
        bbox_inches="tight"
    )

 <i>Reithrodontomys megalotis</i> apresentam semelhança significativa com as espécies <i>Perognathus flavus</i>, <i>Peromyscus eremicus</i> e <i>Peromyscus maniculatus</i>

#### Relação entre peso e comprimento do retropé para distinção de espécies: <i>Sigmodon hispidus</i>

In [72]:
if plotar_comparativos:
  fig, axes = plt.subplots(nrows = 3, ncols = 4, figsize = (24, 15))

  dois_ratos(df_hispidus, df_baileyi, "weight", "hindfoot_length", axes[0, 0])
  dois_ratos(df_hispidus, df_penicillatus, "weight", "hindfoot_length", axes[0, 1])
  dois_ratos(df_hispidus, df_merriami, "weight", "hindfoot_length", axes[0, 2])
  dois_ratos(df_hispidus, df_spectabilis, "weight", "hindfoot_length", axes[0, 3])

  dois_ratos(df_hispidus, df_ordii, "weight", "hindfoot_length", axes[1, 0])
  dois_ratos(df_hispidus, df_albigula, "weight", "hindfoot_length", axes[1, 1])
  dois_ratos(df_hispidus, df_leucogaster, "weight", "hindfoot_length", axes[1, 2])
  dois_ratos(df_hispidus, df_torridus, "weight", "hindfoot_length", axes[1, 3])

  dois_ratos(df_hispidus, df_flavus, "weight", "hindfoot_length", axes[2, 0])
  dois_ratos(df_hispidus, df_eremicus, "weight", "hindfoot_length", axes[2, 1])
  dois_ratos(df_hispidus, df_maniculatus, "weight", "hindfoot_length", axes[2, 2])
  dois_ratos(df_hispidus, df_megalotis, "weight", "hindfoot_length", axes[2, 3])

  if salvar_imagem_graficos:
    plt.savefig(
        "comparacao_hispidus.png",
        dpi=600,
        bbox_inches="tight"
    )

A única espécie que pode ser considerada um pouco semelhante aos <i>Sigmodon hispidus</i> é a <i>Neotoma albigula</i>. Porém, como levantado anteriormente, temos poucos dados sobre os <i>Sigmodon hispidus</i> para afirmar que eles são realmente semelhantes.

## <a id = "dataframe-do-modelo"></a> Dataframe do modelo

Antes de começarmos as discussões sobre o modelo de classificação que vamos desenvolver, precisamos de um dataframe com as informações que vamos utilizar. Para isso, utilizando o método `.merge()` [7], vamos juntar o dataframe dos _P. eremicus_ e o dataframe dos _P. maniculatus_  em um só:

In [73]:
df_modelo = pd.merge(df_eremicus, df_maniculatus, how = 'outer')
df_modelo

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
0,10007,2,17,1985,2,PM,M,20,19,Peromyscus,maniculatus,Rodent,Control
1,10018,2,17,1985,2,PE,F,20,18,Peromyscus,eremicus,Rodent,Control
2,10040,3,16,1985,24,PE,M,18,17,Peromyscus,eremicus,Rodent,Rodent Exclosure
3,10053,3,16,1985,19,PM,F,19,14,Peromyscus,maniculatus,Rodent,Long-term Krat Exclosure
4,10075,3,16,1985,18,PM,F,20,21,Peromyscus,maniculatus,Rodent,Short-term Krat Exclosure
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,9864,1,20,1985,3,PE,M,18,16,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2029,9883,1,20,1985,3,PE,F,20,20,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2030,9933,2,16,1985,12,PE,M,19,40,Peromyscus,eremicus,Rodent,Control
2031,9975,2,16,1985,6,PE,F,20,23,Peromyscus,eremicus,Rodent,Short-term Krat Exclosure


## <a id = "entendendo-o-modelo-knn-vizinhos"></a> Entendendo o modelo knn vizinhos

Ok, já falamos muito de ratos, mas e quanto ao modelo de previsão? O modelo de k-vizinhos mais próximos, também conhecido como k-nearest neighbors, é um classificador de aprendizado supervisionado não-paramétrico. Ele utiliza a distância entre pontos para realizar classificações/previsões sobre o conjunto de um <b>data point$^1$</b> individual. [8]

Apesar de poder ser utilizado tanto para problemas de regressão, quanto para problemas de classificação, o knn é geralmente utilizado para problemas de classificação, supondo que pontos mais parecidos tendem a ficar próximos uns dos outros. Nesses casos, utiliza-se a classificação mais frequente (moda) dos n pontos mais próximos ao ponto que está sendo classificado [8].

Porém, esse modelo não funciona sozinho; ele precisa receber alguns parâmetros. O `KNeighborsClassifier`, do `scikit-learn`, recebe os seguintes parâmetros:
- <b>`n_neighbors`</b> (valor padrão: 5): Número de vizinhos utilizados na consulta de vizinhos mais próximos. Será discutido na seção Número de vizinhos.

- <b>`weights`</b> (valor padrão:'uniform'): Peso dos vizinhos utilizados na predição. Será melhor discutido na sesão Pesos

- <b>`algorithm`</b> (valor padrão: 'auto'): Algoritmo utilizado para calcular os vizinhos mais próximos. Não vamos mexer muito nisso nesse trabalho, então utilizaremos o valor padrão `'auto'`, que vai (tentar) selecionar o melhor algoritmo baseado nos valores passados pelo método `fit()`

- <b>`leaf_size`</b> (valor padrão: 30): Tamanho da folha passado para o `BallTree` ou `KDTree` (ambos são algoritmos, vistos acima). Pode afetar a velocidade da construção e da consulta do modelo, além da memória utilizada para armazenar a árvore criada. O valor ótimo vai depender da natureza do problema. Também não vamos mexer nisso

- <b>`p`</b> (valor padrão: 2): Parâmetro para a métrica `minkowski`, com p = 1 resultando na métrica `manhattan` (L1) e p = 2 resultando na métrica `euclidean` (L2). Para qualquer outro valor de p, é assumida a métrica Lp.

- <b>`metric`</b> (valor padrão: 'minkowski'): Métrica adotada para o cálculo de distância. Será melhor discutida na seção Métricas

- <b>`metric_params`</b> (valor padrão: None): Outras palavras-chaves adicionais para a métrica adotada.

- <b>`n_jobs`</b> (valor padrão: None): Número de jobs paralelos a serem rodados durante a busca.

Todas as informações apresentadas acima foram obtidas do site do scikit-learn, na página a respeito do KNeighborsClassifier. [9]


$^1$ <b>Data points</b> representam uma unidade discreta de informação, ou seja, uma única observação ou um único fato isolado [10].

### <a id = "numero-de-vizinhos"></a> Número de vizinhos

Como o próprio nome sugere, o parâmetro `n_neighbors` é o que determina o número de vizinhos adotados na previsão. Seu valor mínimo é 1, enquanto o seu valor máximo é o número total de observações do nosso dataset. Porém, não é interessante adotar nenhum desses dois extremos - Afinal, se utilizarmos apenas 1 vizinho, ele será muito mais sensível a dados que fogem do padrão e pode levar ao que chamamos de <b>overfitting</b>, o que implica que o modelo é ótimo com os dados de treino, mas não performa bem quando recebe dados novos [11]. Por outro lado, quando adotamos um número de vizinhos muito alto, o modelo pode acabar ignorando padrões locais e levar ao que chamamos de <b>underfitting$^3$</b>, o que implica que o modelo não é bom nem com os dados de teste, nem com os dados de treino [11]. Sendo assim, o número ótimo de vizinhos é algo entre esses dois extremos - e, para encontrá-lo, vamos realizar vários testes, variando o número de vizinhos. [12][13]

### <a id = "pesos"></a> Pesos

Outro atributo do `KNeighborsClassifier`, que iremos utilizar, são os <b>pesos</b> (chamados de <b>weights</b>) de cada ponto. O `KNeighborsClassifier` tem dois "tipos" de peso disponíveis: `uniform` e `distance`.

O tipo de peso `uniform`, como o próprio nome sugere, atribui o mesmo valor (nesse caso, o valor 1) a todos os pontos do modelo, sem considerar pontos que estejam mais próximos ou mais distantes [9]. O tipo `distance`, também como o próprio nome sugere, se importa com a distância dos pontos em relação ao que está sendo previsto. Ele atribui pesos maiores aos pontos que estão mais próximos, e pesos menores aos pontos mais distantes [9].

Nos nossos testes, também iremos variar os pesos considerados pelo nosso modelo.

Depois de todas essas análises que fizemos, chegou a tão esperada hora de escolher quais serão as duas espécies que utilizaremos no nosso modelo. A partir das análises que desenvolvemos, chegamos a conclusão de que as duas espécies mais semelhantes que temos são as <i>Peromyscus eremicus</i> e <i>Peromyscus maniculatus</i>, ambas do mesmo gênero. No dataframe, existem 1198 exemplares dos <i>P. eremicus</i>, e 835 dos <i>P. maniculatus</i>. Sendo assim, mais tarde, será preciso deixar esse dataframe balanceado. Por enquanto, vamos explorar os resultados com os dados desbalanceados mesmo e ver o que acontece

Como temos dataframes individuais de cada uma das nossas espécies, vamos juntar os dataframes das duas espécies em um novo dataframe, chamado `df_modelo`. Para isso, utilizamos o método `.merge()` [5]:

In [74]:
df_modelo = pd.merge(df_eremicus, df_maniculatus, how = 'outer')
df_modelo

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
0,10007,2,17,1985,2,PM,M,20,19,Peromyscus,maniculatus,Rodent,Control
1,10018,2,17,1985,2,PE,F,20,18,Peromyscus,eremicus,Rodent,Control
2,10040,3,16,1985,24,PE,M,18,17,Peromyscus,eremicus,Rodent,Rodent Exclosure
3,10053,3,16,1985,19,PM,F,19,14,Peromyscus,maniculatus,Rodent,Long-term Krat Exclosure
4,10075,3,16,1985,18,PM,F,20,21,Peromyscus,maniculatus,Rodent,Short-term Krat Exclosure
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,9864,1,20,1985,3,PE,M,18,16,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2029,9883,1,20,1985,3,PE,F,20,20,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2030,9933,2,16,1985,12,PE,M,19,40,Peromyscus,eremicus,Rodent,Control
2031,9975,2,16,1985,6,PE,F,20,23,Peromyscus,eremicus,Rodent,Short-term Krat Exclosure


### <a id = "metricas-de-desempenho"></a> Métricas de desempenho

A seguir, iremos discutir algumas das métricas de desempenho disponíveis para o `KNeighborsClassifier`, apresentando a fórmula de cada uma, como elas funcionam, e em quais casos elas são melhores.

Para determinar o quão próximos os casos de treino estão de um caso de teste, o knn utiliza de métricas de distância que quantificam similaridades dentre os valores analisados [14]. Dito isso, existem várias métricas que podem ser utilizadas no `scikit‑learn` para o cálculo de distância, e é isso o que vamos explorar nessa seção.

Iremos discutir 5 métricas diferentes: Minkowski, Euclidiana, Manhattan, Chebyshev e Cosine.

#### Distância Minkowski

A distância Minkowski é uma métrica que funciona tanto quanto a euclidiana, quanto a manhattan, a depender de um parâmetro p em específico [15]. É dada pela seguinte fórmula (3) abaixo [14]:

$$
d(x, y) = ( \sum^n{_i = 1} |x_i - y_i|^p )^{\frac1p} \space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space (3)
$$

Sendo $x$ e $y$ data points, enquanto $p$ é o parâmetro que determina se a métrica adotada será a Euclidiana ou a Manhattan. Quando $p = 1$, a distância Manhattan é adotada. Quando $p = 2$, a distância Euclidiana é adotada. [14] Ela também é a métrica padrão do `KNeighborsClassifier`.

A seguir, veremos a explicação para as métricas de distância euclidiana e manhattan.

#### Distância Euclidiana

A distância euclidiana é definida como a distância, em uma linha reta, entre dois pontos em um plano ou espaço n-dimensional [14], dada pela fórmula (1) apresentada abaixo[14]:

$$
d(x, y) = \sqrt { \sum^n_{i=1} (x_1 - y_i)^2} \space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space (1)
$$

Sendo x e y data points. Essa métrica funciona melhor quando os dados analisados estão normalizados e são de baixa dimensão, além de ser sensível a grandes diferenças nos valores dos atributos.

#### Distância Manhattan

A distância Manhattan é dada pela distância total entre os pontos considerando que só é possível se mover verticalmente ou horizontalmente, como nas ruas de uma cidade ou até mesmo uma grade quadrada [15]. Por esse motivo, essa métrica também pode ser chamada de `cityblock` [16]. Ela é dada pela fórmula (2) apresentada a seguir [14]:

$$
d(x, y) = \sqrt{ \sum^n_{i=1} |x_i - y_i| } \space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space (2)
$$

Sendo x e y datapoints. Essa métrica não é tão afetada por outliers quanto a distância euclidiana (nossos ratinhos massudos agradecem!), além de ser preferida em caso de dados com muitas dimensões [14].

#### Distância Chebyshev

A distância Chebyshev mede a diferença absoluta máxima entre dois pontos [14]. Em outras palavras, ela considera que a distância entre dois pontos é a maior de suas diferenças, ao longo de qualquer dimensão de coordenada [17]. Ela também pode ser chamada de `chessboard distance`, pois, em um jogo de xadrez, o menor número de movimentos possíveis para que um rei ir de uma casa até qualquer outra é igual a distância de Chebyshev entre os centros das casas, caso todas as casas do tabuleiro tenham lado igual a 1 [17]. Sua fórmula é dada pela expressão (4) apresentada a seguir [14]:

$$
d(x, y) = max_i( |p_i - q_i|)) \space\space\space\space\space\space\space\space\space\space\space\space\space\space\space\space (4)
$$

Sendo $x$ e $y$ data points. Essa métrica também ignora variações menores [14].

#### Distância Cosine

A distância de Cosine mede a medida do ângulo entre dois vetores, ao invés de consdierar sua magnitude, dando prioridade ao quão similar as direções de cada um são [16]. É dado pela fórmula:
$$
cos θ = \frac{a*b}{||a||*||b||}
$$
Sendo $a*b$ o produto do ponto, enquanto $||a||*||b||$ representa a magnitude dos vetores.

### <a id = "atributos"></a> Atributos

Antes de seguirmos e testarmos

Já sabemos que os campos `weight` e `hindfoot_length` definitivamente serão atributos utilizados para a previsão do nosso modelo, mas ainda precisamos escolher outros atributos para complementar. Vamos olhar para o nosso dataframe novamente:

In [75]:
df_modelo

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
0,10007,2,17,1985,2,PM,M,20,19,Peromyscus,maniculatus,Rodent,Control
1,10018,2,17,1985,2,PE,F,20,18,Peromyscus,eremicus,Rodent,Control
2,10040,3,16,1985,24,PE,M,18,17,Peromyscus,eremicus,Rodent,Rodent Exclosure
3,10053,3,16,1985,19,PM,F,19,14,Peromyscus,maniculatus,Rodent,Long-term Krat Exclosure
4,10075,3,16,1985,18,PM,F,20,21,Peromyscus,maniculatus,Rodent,Short-term Krat Exclosure
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,9864,1,20,1985,3,PE,M,18,16,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2029,9883,1,20,1985,3,PE,F,20,20,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
2030,9933,2,16,1985,12,PE,M,19,40,Peromyscus,eremicus,Rodent,Control
2031,9975,2,16,1985,6,PE,F,20,23,Peromyscus,eremicus,Rodent,Short-term Krat Exclosure


In [76]:
print("rodou")

rodou


Logo de cara, podemos descartar o `record_id` e o `species_id` como possíveis atributos para a previsão, já que `record_id` é o identificador único de cada indivíduo registrado, e `species_id` entrega a espécie do indivíduo, que é o nosso target, o que não é interessante para o nosso modelo.

Também não é interessante utilizar o campo `genus`, já que, nesse caso, ambas as espécies são do gênero <i>Peromyscus</i>. Ainda assim, caso fossem espécies de gêneros taxônomicos diferentes, ainda não seria interessante, já que isso iria "entregar" a espécie do animal. Não iremos utilizar o campo `taxa` pelo mesmo motivo, já que ambos os ratinhos escolhidos são roedores.

Também temos as colunas com dados referentes à data que cada ratinho foi catalogado: `day`, `month` e `year`. Utilizar o dia isolado não parece ser muito interessante, e, a primeira vista, mês e ano também não. No entanto, o mês e o ano podem trazer alguma perspectiva interessante sobre períodos de mais registro de cada espécie ou até de períodos de maior atividade, então iremos considerá-los como atributos. Mas também pode, talvez, quem sabe, acontecer de que essas duas métricas mais nos atrapalhem do que nos ajudem...

Os atributos `plot_id` e `plot_type` estão relacionados à mesma coisa: a classificação do espaço em que o animal foi encontrado. Porém, existe mais de um "espaço" para cada tipo, o que é representado pelo `plot_id`, que numera as áreas de estudo. Enquanto isso, o `plot_type` descreve apenas o tipo de área, mas não dá informações sobre qual área em específico aquele animal foi registrado. Sendo assim, acredito ser mais interessante considerar apenas um dos dois dados sobre o `plot`.

O atributo `sex` também pode ser interessante, já que o tamanho dos ratos pode variar de acordo com seu sexo, como vimos anteriormente.

Faremos testes com vários conjuntos de atributos diferentes, variando quais são considerados e quais não são. Ao mesmo tempo, vamos variar as métricas, os pesos e os números de vizinhos do modelo.

### Normalizando dados categóricos

In [77]:
print("rodou")

rodou


Porém, o knn funciona com base em distâncias, ou seja, ele não aceita colunas com dados categóricos, apenas dados numéricos. Sendo assim, precisamos transformar as colunas `plot_type`e `sex` em dados numéricos. Faremos isso com o método `OneHotEncoder`, que converte dados categóricos em numéricos criando uma coluna para cada categoria observada. Estas colunas dados binários (0 ou 1), sendo que 1 representa o que aquele atributo era antes da conversão [17].

#### O novo data frame

Para evitar possíveis confusões, vamos criar um novo dataframe, de nome diferente:

In [78]:
tamanho_sample = 800

e1_aleatorios = df_eremicus.sample(tamanho_sample, random_state = SEMENTE_ALEATORIA)
e2_aleatorios = df_maniculatus.sample(tamanho_sample, random_state = SEMENTE_ALEATORIA)

df_modelo_balanceado = pd.merge(e1_aleatorios, e2_aleatorios, how = 'outer')
df_modelo_balanceado

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
0,10040,3,16,1985,24,PE,M,18,17,Peromyscus,eremicus,Rodent,Rodent Exclosure
1,10053,3,16,1985,19,PM,F,19,14,Peromyscus,maniculatus,Rodent,Long-term Krat Exclosure
2,10075,3,16,1985,18,PM,F,20,21,Peromyscus,maniculatus,Rodent,Short-term Krat Exclosure
3,10087,3,17,1985,3,PE,F,20,26,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
4,10090,3,17,1985,15,PM,M,20,16,Peromyscus,maniculatus,Rodent,Long-term Krat Exclosure
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,9833,1,19,1985,14,PM,F,21,22,Peromyscus,maniculatus,Rodent,Control
1596,9864,1,20,1985,3,PE,M,18,16,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
1597,9883,1,20,1985,3,PE,F,20,20,Peromyscus,eremicus,Rodent,Long-term Krat Exclosure
1598,9933,2,16,1985,12,PE,M,19,40,Peromyscus,eremicus,Rodent,Control


Mas também vamos transformar os dados de `plot_type` e `sex` em números novamente, com o mesmo procedimento que fizemos antes, quando os dados não eram balanceados:

In [79]:
df_modelo_balanceado['plot_type'] = pd.factorize(df_modelo_balanceado['plot_type'])[0] + 1
df_modelo_balanceado['sex'] = pd.factorize(df_modelo_balanceado['sex'])[0] + 1

df_modelo_balanceado

,record_id,month,day,year,plot_id,species_id,sex,hindfoot_length,weight,genus,species,taxa,plot_type
0,10040,3,16,1985,24,PE,1,18,17,Peromyscus,eremicus,Rodent,1
1,10053,3,16,1985,19,PM,2,19,14,Peromyscus,maniculatus,Rodent,2
2,10075,3,16,1985,18,PM,2,20,21,Peromyscus,maniculatus,Rodent,3
3,10087,3,17,1985,3,PE,2,20,26,Peromyscus,eremicus,Rodent,2
4,10090,3,17,1985,15,PM,1,20,16,Peromyscus,maniculatus,Rodent,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1595,9833,1,19,1985,14,PM,2,21,22,Peromyscus,maniculatus,Rodent,4
1596,9864,1,20,1985,3,PE,1,18,16,Peromyscus,eremicus,Rodent,2
1597,9883,1,20,1985,3,PE,2,20,20,Peromyscus,eremicus,Rodent,2
1598,9933,2,16,1985,12,PE,1,19,40,Peromyscus,eremicus,Rodent,4


In [80]:
METRICA = "manhattan"
NUM_TESTES_VIZINHOS = 10

modelo_topissimo_manhattan_balanceado = testa_atributos_modelo(
    conjunto_sem_data,
    METRICA,
    NUM_TESTES_VIZINHOS,
    imprimir_resultados = True,
    df = df_modelo_balanceado
    )


print("\nMelhor modelo de distância manhattan encontrado:")
print(f"Número de vizinhos: {modelo_topissimo_manhattan_balanceado["vizinhos"]}")
print(f"Pesos: {modelo_topissimo_manhattan_balanceado["peso"]}")
print(f"Acurácia: {modelo_topissimo_manhattan_balanceado["acurácia"]}%")
print(f"Atributos: {modelo_topissimo_manhattan_balanceado["atributos"]}")


NameError: name 'testa_atributos_modelo' is not defined

Para a métrica de distância manhattan, o melhor modelo encontrado foi com 9 vizinhos, pesos uniformes e utilizando o peso, medida de retropé, id e tipo da área em que foi encontrado como atributos. Esse modelo obteve uma acurácia de `70.62%`, sendo melhor do que o melhor modelo de métrica manhattan quando os dados estavam desbalanceados, que era de `69.12%`.

O pior conjunto de dados também foi o que utilizou peso, medida de retropé e sexo como atributos, com `52.50%` de acurácia. É interessante que o pior conjunto na métrica euclidiana também foi o pior conjunto na métrica manhattan. Sabemos que o peso e medida de retropé dessas duas espécies são bem parecidos (afinal, é por isso que escolhemos elas!), e as distribuições de sexo entre as duas também não devem ser muito diferentes. É interessante ver que, quando isolados, esses três não são bons parâmetros.

Organizando as acurácias obtidas, junto com seus conjuntos de atributos, nós temos:

```
- 52.5% - ['weight', 'hindfoot_length', 'sex']
- 56.25% - ['weight', 'hindfoot_length']
- 56.25% - ['weight', 'hindfoot_length', 'plot_type', 'sex']
- 58.13% - ['weight', 'hindfoot_length', 'plot_type']
- 68.75% - ['weight', 'hindfoot_length', 'plot_id']
- 66.88% - ['weight', 'hindfoot_length', 'plot_id', 'sex']
- 66.88% - ['weight', 'hindfoot_length', 'plot_type', 'sex', 'plot_id']
- 70.62% - ['weight', 'hindfoot_length', 'plot_id', 'plot_type']
```

O que é mais interessante ainda, é ver que a ordem de melhores acurácias para as métricas euclidiana e manhattan é a mesma. (!!!!)

In [ ]:
METRICA = "cosine"
NUM_TESTES_VIZINHOS = 10

modelo_topissimo_cosine_balanceado = testa_atributos_modelo(
    conjunto_sem_data,
    METRICA,
    NUM_TESTES_VIZINHOS,
    imprimir_resultados = True,
    df = df_modelo_balanceado
    )


print("\nMelhor modelo de distância cosine encontrado:")
print(f"Número de vizinhos: {modelo_topissimo_cosine_balanceado["vizinhos"]}")
print(f"Pesos: {modelo_topissimo_cosine_balanceado["peso"]}")
print(f"Acurácia: {modelo_topissimo_cosine_balanceado["acurácia"]}%")
print(f"Atributos: {modelo_topissimo_cosine_balanceado["atributos"]}")

Para a métrica de distância cosine, o melhor modelo encontrado foi com 5 vizinhos, pesos uniformes e utilizando o peso, medida de retropé, id e tipo da área em que foi encontrado, e sexo como atributos. Esse modelo obteve uma acurácia de `67.50%`, sendo um pouco pior do que o modelo com dados desbalanceados, que era de `70.10%`.

O pior conjunto de dados também foi o que utilizou apenas peso e medida de retropé como atributos, com uma acurácia de `53.12%`. O segundo pior utilizava peso, retropé e sexo, com `54.37%` de acurácia

Organizando as acurácias obtidas, junto com seus conjuntos de atributos, obtemos:

```
- 53.12% - ['weight', 'hindfoot_length']
- 54.37% - ['weight', 'hindfoot_length', 'sex']
- 58.75% - ['weight', 'hindfoot_length', 'plot_type', 'sex']
- 60.62% - ['weight', 'hindfoot_length', 'plot_type']
- 60.62% - ['weight', 'hindfoot_length', 'plot_id']
- 63.75% - ['weight', 'hindfoot_length', 'plot_id', 'sex']
- 64.38% - ['weight', 'hindfoot_length', 'plot_id', 'plot_type']
- 67.5% - ['weight', 'hindfoot_length', 'plot_type', 'sex', 'plot_id']
```  
A ordem de melhores acurácias não é mais a mesma: o melhor conjunto para as métricas euclidiana e manhattan, ocupa o segundo lugar. Embora a ordem não seja exatamente a mesma, houveram pequenas inversões entre o último e o penúltimo lugar, o mesmo com o primeiro e segundo lugar. Os lugares do meio também deram uma leve trocada de lugar.

In [ ]:
METRICA = "chebyshev"
NUM_TESTES_VIZINHOS = 10

modelo_topissimo_chebyshev_balanceado = testa_atributos_modelo(
    conjunto_sem_data,
    METRICA,
    NUM_TESTES_VIZINHOS,
    imprimir_resultados = True,
    df = df_modelo_balanceado
    )


print("\nMelhor modelo de distância chebyshev encontrado:")
print(f"Número de vizinhos: {modelo_topissimo_chebyshev_balanceado["vizinhos"]}")
print(f"Pesos: {modelo_topissimo_chebyshev_balanceado["peso"]}")
print(f"Acurácia: {modelo_topissimo_chebyshev_balanceado["acurácia"]}%")
print(f"Atributos: {modelo_topissimo_chebyshev_balanceado["atributos"]}")

Para a métrica de distância chebyshev, o melhor modelo encontrado foi com 15 vizinhos, pesos uniformes e utilizando o peso, medida de retropé, id e tipo da área em que foi encontrado, e sexo como atributos. Esse modelo obteve uma acurácia de `65.00%`, sendo a que mais diminuiu após o balanceamento dos dados. Antes dos dados serem balanceados, a acurácia do melhor modelo com a métrica de chebyshev era de `71.08%`.

O pior conjunto de dados foi o que utilizou peso, medida de retropé e sexo como atributos, com uma acurácia de `50.62%`. É bem pouco melhor do que jogar uma moeda...

Organizando as acurácias obtidas, junto com seus conjuntos de atributos, obtemos:
```
- 50.62% - ['weight', 'hindfoot_length', 'sex']
- 55.00% - ['weight', 'hindfoot_length', 'plot_type', 'sex']
- 56.25% - ['weight', 'hindfoot_length']
- 59.38% - ['weight', 'hindfoot_length', 'plot_type']
- 62.50% - ['weight', 'hindfoot_length', 'plot_id']
- 62.50% - ['weight', 'hindfoot_length', 'plot_id', 'sex']
- 64.38% - ['weight', 'hindfoot_length', 'plot_id', 'plot_type']
- 65.00% - ['weight', 'hindfoot_length', 'plot_type', 'sex', 'plot_id']
```

De todos, esse é o que a ordem de maiores acurácias mais mudou. O peso e retropé agora são o antipenúltimo lugar, e peso, retropé, tipo de área e sexo ocupam o penúltimo lugar. A métrica de chebyshev também foi a com o pior desempenho dentre as quatro.

In [86]:
from sklearn.preprocessing import OneHotEncoder
converter_plottype = df_modelo[["plot_type"]]

# cria uma instância do encoder
encoder = OneHotEncoder(sparse_output = False)

# ajusta o  aos dados
encoder.fit(converter_plottype)
colunas = encoder.categories_

# aplica o encoder usando o método `transform`
dados_plot_convertidos = encoder.transform(converter_plottype)

df_plot_convertido = pd.DataFrame(dados_plot_convertidos, columns = colunas)
df_plot_convertido

,Control,Long-term Krat Exclosure,Rodent Exclosure,Short-term Krat Exclosure,Spectab exclosure
0,1.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,1.0,0.0,0.0
3,0.0,1.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...
2028,0.0,1.0,0.0,0.0,0.0
2029,0.0,1.0,0.0,0.0,0.0
2030,1.0,0.0,0.0,0.0,0.0
2031,0.0,0.0,0.0,1.0,0.0


In [85]:
converter_sexo = df_modelo[["sex"]]

# cria uma instância do encoder
encoder = OneHotEncoder(sparse_output = False)

# ajusta o  aos dados
encoder.fit(converter_sexo)
colunas = encoder.categories_

# aplica o encoder usando o método `transform`
dados_sexo_convertidos = encoder.transform(converter_sexo)

df_sexo_convertido = pd.DataFrame(dados_sexo_convertidos, columns = colunas)
df_sexo_convertido

,F,M
0,0.0,1.0
1,1.0,0.0
2,0.0,1.0
3,1.0,0.0
4,1.0,0.0
...,...,...
2028,0.0,1.0
2029,1.0,0.0
2030,0.0,1.0
2031,1.0,0.0


Agora, vamos juntar os dois dataframes acima com o dataframe do modelo, criando um novo dataframe de modelo. Como a coluna `plot_type` se transformou em 5 colunas, e a coluna `sex` virou duas, agora nós temos 18 colunas em nosso dataframe.

In [84]:
df_modelo_convertido = pd.concat([df_modelo.drop(columns = ["sex", "plot_type"]), df_sexo_convertido, df_plot_convertido], axis = 1)
df_modelo_convertido

,record_id,month,day,year,plot_id,species_id,hindfoot_length,weight,genus,species,taxa,"(F,)","(M,)","(Control,)","(Long-term Krat Exclosure,)","(Rodent Exclosure,)","(Short-term Krat Exclosure,)","(Spectab exclosure,)"
0,10007,2,17,1985,2,PM,20,19,Peromyscus,maniculatus,Rodent,0.0,1.0,1.0,0.0,0.0,0.0,0.0
1,10018,2,17,1985,2,PE,20,18,Peromyscus,eremicus,Rodent,1.0,0.0,1.0,0.0,0.0,0.0,0.0
2,10040,3,16,1985,24,PE,18,17,Peromyscus,eremicus,Rodent,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,10053,3,16,1985,19,PM,19,14,Peromyscus,maniculatus,Rodent,1.0,0.0,0.0,1.0,0.0,0.0,0.0
4,10075,3,16,1985,18,PM,20,21,Peromyscus,maniculatus,Rodent,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2028,9864,1,20,1985,3,PE,18,16,Peromyscus,eremicus,Rodent,0.0,1.0,0.0,1.0,0.0,0.0,0.0
2029,9883,1,20,1985,3,PE,20,20,Peromyscus,eremicus,Rodent,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2030,9933,2,16,1985,12,PE,19,40,Peromyscus,eremicus,Rodent,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2031,9975,2,16,1985,6,PE,20,23,Peromyscus,eremicus,Rodent,1.0,0.0,0.0,0.0,0.0,1.0,0.0


## <a id = "planos-futuros"></a> Planos futuros

Futuramente, é interessante testar e desenvolver novos modelos que utilizem de diferentes estratégias e métodos para normalizar os dados da tabela, como o `StandardScaler` ou `MinMaxScaler`. Também é interessante que, futuramente, sejam testadas outras maneiras de converter os dados categóricos em dados numéricos que sejam considerados pelo knn.

## <a id = "conclusoes"></a>Conclusões e principais aprendizados

Por fim, depois de tantas análises, gráficos, discussões e mais análises, podemos concluir que o modelo desenvolvido apresenta uma acurácia satisfatória para a tarefa proposta, além de performar melhor do que um modelo baseline com os mesmos atributos. Além disso, também houve aprendizado significativo acerca de como decidir os atributos que devem entrar no modelo de classificação, sobre como considerar o que era um atributo relevante para o que estava sendo classificado (no caso, o rato), e quais eram informações da tabela, mas que não diziam nada sobre os roedores em si. Também houve aprendizado sobre as métricas do knn abordadas, os pesos e número de vizinhos na construção de um modelo. Houve também maior aprendizado sobre representações gráficas e maneiras de deixá-las mais compactas, como com o uso de paineis. Também houve, claro, grande aprendizado sobre as espécies de roedores abordadas no trabalho.

## <a id = "uso-ia"></a> Descrição do uso de IA neste trabalho

As ferramentas de inteligência artificial Chat GPT e Copilot foram utilizadas para encontrar um dataset que cumprisse os requisitos estabelecidos pelo professor, e que também fossem do meu interesse. A ferramenta Chat GPT também foi utilizada para encontrar sites que possuissem mais informações sobre o dataset escolhido, tal qual o que cada coluna representava. O Chat GPT também foi utilizado para auxílio no desenvolvimento dos códigos das funções para plotar gráficos sobre o peso e medidas de retropé dos roedores, principalmente no scatterplot comparativo de duas espécies distintas. Ainda nas representações gráficas, o Chat GPT foi utilizado para discussão de possíveis títulos para o painel de gráficos comparativos. A ferramenta Gemini foi utilizada por meio das pesquisas realizadas no Google, mas seus resultados foram utilizados para encontrar sites que continham informações relevantes à questão pesquisada. Também houve uma tentativa de utilizar o Chat GPT para organizar as referências por ordem que elas apareciam no texto, mas sem sucesso.

## <a id = "referencias"></a>Referências

- [1] Portal Project Teaching Database, National Science Foundation. Disponível em: https://figshare.com/articles/dataset/Portal_Project_Teaching_Database/1314459

- [2] Scikit-learn, Getting Started. Disponível em: https://scikit-learn.org/stable/getting_started.html

- [3] Ratdat, Package 'ratdat'. Disponível em: https://cran.r-project.org/web/packages/ratdat/ratdat.pdf

- [4] LaBex, How to filter data in a Pandas DataFrame based on conditions. Disponível em: https://labex.io/tutorials/python-how-to-filter-data-in-a-pandas-dataframe-based-on-conditions-395062

- [5] Stack overflow, Convert Pandas DataFrame Column From String to Int Based on Conditional. Disponível em: https://stackoverflow.com/questions/31790287/convert-pandas-dataframe-column-from-string-to-int-based-on-conditional

- [6] Wikipédia, Correlação de Pearson. Disponível em: https://pt.wikipedia.org/wiki/Coeficiente_de_correla%C3%A7%C3%A3o_de_Pearson

- [7] Stack overflow, Juntar dois dataframes de mesmo nome mantendo todas as colunas. Disponível em: https://pt.stackoverflow.com/questions/515603/juntar-dois-dataframes-de-mesmo-nome-mantendo-todas-as-colunas

- [8] IBM, What is the k-nearest neighbors (KNN) algorithm?. Disponível em: https://www.ibm.com/think/topics/knn

- [9] Scikit-Learn documentation, KNeighborsClassifier. Disponível em: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

- [10] Tech target, datapoint definition. Disponível em: https://www.techtarget.com/whatis/definition/data-point

- [11] Codecademy, K-Nearest Neighbors. Disponível em: https://www.codecademy.com/learn/introduction-to-supervised-learning-skill-path-2024/modules/k-nearest-neighbors-skill-path/cheatsheet

- [12] Medium, The Art of Choosing K in KNN Models. Disponível em: https://medium.com/@akshada512.patil/the-art-of-choosing-k-in-knn-models-aac6bc202c51

- [13] Towards data science, Choosing the Right Number of Neighbors (k) for the K-Nearest Neighbors (KNN) Algorithm. Disponível em: https://towardsdatascience.com/choosing-the-right-number-of-neighbors-k-for-the-k-nearest-neighbors-knn-algorithm-fbc635279ec7/

- [14] Geeks for geeks, How to choose the right distance metric in KNN?. Disponível em: https://www.geeksforgeeks.org/machine-learning/how-to-choose-the-right-distance-metric-in-knn/

- [15] Geeks for geeks, K-Nearest Neighbor(KNN) Algorithm. Disponível em: https://www.geeksforgeeks.org/machine-learning/k-nearest-neighbours/

- [16] Scikit-learn documentation, distance_metrics. Disponível em: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.distance_metrics.html#sklearn.metrics.pairwise.distance_metrics

- [17] Material de aula da disciplina. 1.1 - Tratamento de dados com pandas.

- [18] Wikipédia, Chebyshev distance. Disponível em: https://en.wikipedia.org/wiki/Chebyshev_distance

- [19] Stack Overflow, Fazer um random de um dataset com pandas. Disponível em: https://pt.stackoverflow.com/questions/324588/fazer-um-random-de-um-dataset-com-pandas

- [20] Stack Overflow, How to make a seed to pd.sample like np.random.seed?. Disponível em: https://stackoverflow.com/questions/55748741/how-to-make-a-seed-to-pd-sample-like-np-random-seed

## <a id = "agradecimentos"></a>Agradecimentos especiais

- Minha mãe, Iara Fernandes, por ter sugerido por muitas semanas que eu fizesse o Coeficiente de Pearson para os meus ratos (e que também aguentou me ouvir falar sobre ratos em muitos almoços);
- Meu pai, Renato Cano, que mesmo dizendo que não aguentava mais me ouvir falar sobre os ratos, continuou ouvindo mesmo assim;
- Leonardo Gomes, minha dupla de Iniciação a Pesquisa, por sugerir que eu colocasse os gráficos de comparação entre espécies de rato em um grande painel, agrupando-as por espécie comparada, ao invés de plotar 78 gráficos individuais e ter que discutir cada um deles;
- Mariana Melo, minha veterana(❤️), por também ter sugerido que eu fizesse um painel de gráficos;
- Jéssika Nóbrega, minha colega de sala, por sugestões quanto às cores utilizadas nas representações gráficas. Afinal, a paleta flavus realmente tem mais cara de deserto do que a paleta viridis;
- Angel Andrade, minha colega de sala, por ter me ouvido falar de ratos e analisado gráficos de ratos comigo por um período não razoável de tempo, e uma quantidade também não razoável de vezes;
- Isabela Leme, minha colega de sala e de quarto, por me dar uma ideia de como eu poderia testar diferentes parâmetros e compará-los;
- Maria Vitória, minha colega de sala, por me mostrar como mudar a paleta de cores do heatmap da matriz de confusão com o  `cmap`;
- Matheus Velloso, um de meus veteranos, por me ajudar na discussão de mês e ano serem ou não parâmetros válidos, e o porquê disso;
- Brenda Abrunhosa, uma de minhas veteranas, por trazer uma boa perspectiva sobre o motivo da acurácia diminuir quando os dados eram balanceados, e por falar que as cores dos scatterplots comparativos eram "bem ilum"